"""Alert Manager for PriorityWorker Monitoring

Monitors daemon health and sends alerts on failures.
Clean Architecture: Adapter layer (external notification systems)
SOLID: SRP (alerting only), DIP (depends on alert channel abstractions)

Generated from ULTRATHINK design on 2025-10-04.
"""

import os
import subprocess
import time
import smtplib
import requests
from datetime import datetime, timedelta
from typing import Dict, Any, List, Optional, Protocol
from pathlib import Path
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


class AlertChannel(Protocol):
    """Protocol for alert delivery channels (ISP)."""

    def send_alert(self, title: str, message: str, severity: str) -> bool:
        """Send alert via this channel. Returns True if successful."""
        ...


class EmailAlertChannel:
    """Email notification channel via SMTP."""

    def __init__(self, config: Dict[str, Any]):
        """Initialize email channel with SMTP configuration.

        Args:
            config: Email configuration
                - smtp_host: SMTP server hostname
                - smtp_port: SMTP server port (default 587)
                - smtp_user: SMTP username
                - smtp_password: SMTP password
                - from_address: Sender email address
                - to_addresses: List of recipient addresses
                - use_tls: Enable TLS (default True)
        """
        self.smtp_host = config['smtp_host']
        self.smtp_port = config.get('smtp_port', 587)
        self.smtp_user = config['smtp_user']
        self.smtp_password = config['smtp_password']
        self.from_address = config['from_address']
        self.to_addresses = config['to_addresses']
        self.use_tls = config.get('use_tls', True)

    def send_alert(self, title: str, message: str, severity: str) -> bool:
        """Send email alert."""
        try:
            msg = MIMEMultipart()
            msg['From'] = self.from_address
            msg['To'] = ', '.join(self.to_addresses)
            msg['Subject'] = f"[{severity.upper()}] PriorityWorker Alert: {title}"

            body = f"""
PriorityWorker Alert
====================

Severity: {severity.upper()}
Time: {datetime.utcnow().isoformat()}
Alert: {title}

Details:
{message}

---
Generated by autonomous-task-agent-dev-orchestration alerting system
"""
            msg.attach(MIMEText(body, 'plain'))

            server = smtplib.SMTP(self.smtp_host, self.smtp_port)
            if self.use_tls:
                server.starttls()
            server.login(self.smtp_user, self.smtp_password)
            server.send_message(msg)
            server.quit()

            return True

        except Exception as e:
            print(f"Email alert failed: {e}")
            return False


class WebhookAlertChannel:
    """Webhook notification channel (Slack, Discord, etc)."""

    def __init__(self, config: Dict[str, Any]):
        """Initialize webhook channel.

        Args:
            config: Webhook configuration
                - webhook_url: Webhook URL
                - webhook_type: Type (slack, discord, generic)
                - timeout: Request timeout seconds (default 5)
        """
        self.webhook_url = config['webhook_url']
        self.webhook_type = config.get('webhook_type', 'generic')
        self.timeout = config.get('timeout', 5)

    def send_alert(self, title: str, message: str, severity: str) -> bool:
        """Send webhook alert."""
        try:
            # Format payload based on webhook type
            if self.webhook_type == 'slack':
                payload = self._format_slack(title, message, severity)
            elif self.webhook_type == 'discord':
                payload = self._format_discord(title, message, severity)
            else:
                payload = {
                    'title': title,
                    'message': message,
                    'severity': severity,
                    'timestamp': datetime.utcnow().isoformat()
                }

            response = requests.post(
                self.webhook_url,
                json=payload,
                timeout=self.timeout
            )
            response.raise_for_status()
            return True

        except Exception as e:
            print(f"Webhook alert failed: {e}")
            return False

    def _format_slack(self, title: str, message: str, severity: str) -> Dict:
        """Format Slack message payload."""
        color = {
            'critical': 'danger',
            'warning': 'warning',
            'info': 'good'
        }.get(severity, 'warning')

        return {
            'attachments': [{
                'color': color,
                'title': f"PriorityWorker Alert: {title}",
                'text': message,
                'fields': [
                    {'title': 'Severity', 'value': severity.upper(), 'short': True},
                    {'title': 'Time', 'value': datetime.utcnow().isoformat(), 'short': True}
                ]
            }]
        }

    def _format_discord(self, title: str, message: str, severity: str) -> Dict:
        """Format Discord message payload."""
        color_map = {
            'critical': 15158332,  # Red
            'warning': 16776960,   # Yellow
            'info': 3447003        # Blue
        }

        return {
            'embeds': [{
                'title': f"PriorityWorker Alert: {title}",
                'description': message,
                'color': color_map.get(severity, 16776960),
                'fields': [
                    {'name': 'Severity', 'value': severity.upper(), 'inline': True},
                    {'name': 'Time', 'value': datetime.utcnow().isoformat(), 'inline': True}
                ]
            }]
        }


class LogAlertChannel:
    """Log-based alert channel (fallback)."""

    def __init__(self, config: Dict[str, Any]):
        """Initialize log channel.

        Args:
            config: Log configuration
                - log_file: Path to alert log file
        """
        self.log_file = Path(config.get('log_file', 'logs/priority_worker_alerts.log'))
        self.log_file.parent.mkdir(parents=True, exist_ok=True)

    def send_alert(self, title: str, message: str, severity: str) -> bool:
        """Write alert to log file."""
        try:
            timestamp = datetime.utcnow().isoformat()
            log_entry = f"[{timestamp}] [{severity.upper()}] {title}\n{message}\n\n"

            with open(self.log_file, 'a') as f:
                f.write(log_entry)

            return True

        except Exception as e:
            print(f"Log alert failed: {e}")
            return False


class AlertManager:
    """Manages alert monitoring and delivery for PriorityWorker.

    Monitors health check script and metrics, sends alerts via configured channels.
    Implements rate limiting to avoid alert spam.
    """

    def __init__(self, config: Dict[str, Any]):
        """Initialize AlertManager with configuration.

        Args:
            config: Alert configuration
                - channels: List of alert channel configs
                - thresholds: Alert threshold configuration
                - rate_limit_seconds: Min time between duplicate alerts
                - health_check_script: Path to health check script
                - log_file: Path to daemon log file
        """
        self.config = config
        self.channels: List[AlertChannel] = []
        self.alert_history: Dict[str, float] = {}  # alert_key -> last_sent_timestamp
        self.rate_limit = config.get('rate_limit_seconds', 300)  # 5 minutes default
        self.health_check_script = Path(config.get('health_check_script', 'scripts/health_check.sh'))
        self.log_file = Path(config.get('log_file', 'logs/priority_worker_production.log'))

        # Initialize alert channels
        self._init_channels(config.get('channels', []))

        # Thresholds
        self.thresholds = config.get('thresholds', {
            'failure_rate_percent': 20,
            'memory_mb': 500,
            'cycle_timeout_seconds': 300
        })

    def _init_channels(self, channel_configs: List[Dict[str, Any]]):
        """Initialize alert channels from configuration."""
        for channel_config in channel_configs:
            channel_type = channel_config.get('type')

            if channel_type == 'email':
                self.channels.append(EmailAlertChannel(channel_config))
            elif channel_type == 'webhook':
                self.channels.append(WebhookAlertChannel(channel_config))
            elif channel_type == 'log':
                self.channels.append(LogAlertChannel(channel_config))
            else:
                print(f"Unknown channel type: {channel_type}")

        # Always add log channel as fallback
        if not any(isinstance(ch, LogAlertChannel) for ch in self.channels):
            self.channels.append(LogAlertChannel({'log_file': 'logs/priority_worker_alerts.log'}))

    def check_and_alert(self):
        """Run all health checks and send alerts if needed."""
        # Check process health via health check script
        health_status = self._run_health_check()
        if health_status == 1:  # Unhealthy
            self._send_alert(
                'process_crash',
                'Process Crash Detected',
                'PriorityWorker process is not running or unhealthy',
                'critical'
            )
        elif health_status == 2:  # Warning
            self._check_health_warnings()

        # Check failure rate from logs
        self._check_failure_rate()

    def _run_health_check(self) -> int:
        """Run health check script and return exit code."""
        try:
            result = subprocess.run(
                [str(self.health_check_script)],
                capture_output=True,
                timeout=30
            )
            return result.returncode
        except Exception as e:
            print(f"Health check script failed: {e}")
            return 1  # Treat as unhealthy

    def _check_health_warnings(self):
        """Parse health check output for specific warnings."""
        try:
            result = subprocess.run(
                [str(self.health_check_script)],
                capture_output=True,
                text=True,
                timeout=30
            )

            output = result.stdout + result.stderr

            # Check for high memory
            if 'High memory usage' in output:
                self._send_alert(
                    'high_memory',
                    'High Memory Usage',
                    f"Memory usage exceeds {self.thresholds['memory_mb']}MB threshold",
                    'warning'
                )

            # Check for low disk space
            if 'Low disk space' in output:
                self._send_alert(
                    'low_disk',
                    'Low Disk Space',
                    'Disk space below 100MB threshold',
                    'warning'
                )

        except Exception as e:
            print(f"Warning check failed: {e}")

    def _check_failure_rate(self):
        """Check task failure rate from recent logs."""
        try:
            if not self.log_file.exists():
                return

            # Read last 100 lines
            result = subprocess.run(
                ['tail', '-100', str(self.log_file)],
                capture_output=True,
                text=True
            )

            lines = result.stdout.split('\n')
            total_tasks = 0
            failed_tasks = 0

            for line in lines:
                if 'Task completed:' in line or 'Task failed:' in line:
                    total_tasks += 1
                    if 'Task failed:' in line:
                        failed_tasks += 1

            if total_tasks > 0:
                failure_rate = (failed_tasks / total_tasks) * 100
                threshold = self.thresholds['failure_rate_percent']

                if failure_rate > threshold:
                    self._send_alert(
                        'high_failure_rate',
                        'High Task Failure Rate',
                        f"Failure rate: {failure_rate:.1f}% (threshold: {threshold}%)\n"
                        f"Failed: {failed_tasks}/{total_tasks} tasks",
                        'critical'
                    )

        except Exception as e:
            print(f"Failure rate check failed: {e}")

    def _send_alert(self, alert_key: str, title: str, message: str, severity: str):
        """Send alert via all channels with rate limiting.

        Args:
            alert_key: Unique key for rate limiting
            title: Alert title
            message: Alert message
            severity: Severity level (critical, warning, info)
        """
        # Check rate limit
        now = time.time()
        last_sent = self.alert_history.get(alert_key, 0)

        if now - last_sent < self.rate_limit:
            return  # Skip duplicate alert within rate limit

        # Send via all channels
        success = False
        for channel in self.channels:
            if channel.send_alert(title, message, severity):
                success = True

        if success:
            self.alert_history[alert_key] = now
            print(f"Alert sent: {title} (severity: {severity})")

    def monitor_loop(self, interval_seconds: int = 60):
        """Run continuous monitoring loop.

        Args:
            interval_seconds: Check interval in seconds
        """
        print(f"AlertManager started, checking every {interval_seconds}s")

        while True:
            try:
                self.check_and_alert()
            except Exception as e:
                print(f"Monitoring error: {e}")

            time.sleep(interval_seconds)
