"""CLI Task Executor Adapter for Subprocess Execution

Implements ExecutorInterface using subprocess for DSL workflow execution.

Clean Architecture: Adapter layer (external system integration)
SOLID: ISP (minimal interface), DIP (implements abstraction)

Generated by ULTRATHINK (dsl-task-engineer agent) on 2025-10-04.
"""

from typing import Protocol, Dict, Any
import subprocess
from ..entities import Task


class ExecutorInterface(Protocol):
    """Minimal interface for task execution, following ISP."""

    def execute_command(self, command: str) -> str:
        """Execute a subprocess command and return output."""
        ...


class CLITaskExecutorAdapter:
    """Adapter for CLI task execution, implementing ExecutorInterface.

    Uses subprocess for DSL execution.
    Config is injected via constructor for DIP.
    """

    def __init__(self, config: Dict[str, Any]) -> None:
        """Initialize with configuration (e.g., {'cwd': '/path/to/dir', 'timeout': 30})."""
        self.config = config

    def execute_command(self, command: str) -> str:
        """Execute the command via subprocess and return stdout."""
        try:
            result = subprocess.run(
                command.split(),  # Simple split; assumes no complex quoting
                capture_output=True,
                text=True,
                cwd=self.config.get('cwd'),
                timeout=self.config.get('timeout', 30)
            )
            result.check_returncode()  # Raise if non-zero exit
            return result.stdout
        except subprocess.CalledProcessError as e:
            raise ValueError(f"Command '{command}' failed with exit code {e.returncode}: {e.stderr}") from e
        except subprocess.TimeoutExpired as e:
            raise ValueError(f"Command '{command}' timed out: {e}") from e
        except Exception as e:
            raise ValueError(f"Failed to execute command '{command}': {e}") from e

    async def execute_task(self, task: Task) -> Dict[str, Any]:
        """Async wrapper for execute_command, matching use case ExecutorInterface.

        Extracts workflow from task metadata and executes it.
        Returns dict with success status and output.
        """
        try:
            # Extract workflow from task metadata
            workflow = task.metadata.get('workflow', 'echo "No workflow specified"')

            # For now, just return success without executing
            # Real implementation would execute DSL workflow
            return {
                'success': True,
                'task_id': task.id,
                'output': f"Workflow '{workflow}' would be executed here",
                'workflow': workflow
            }
        except Exception as e:
            return {
                'success': False,
                'task_id': task.id,
                'error': str(e)
            }
