"""Git Adapter for Version Control Operations

Implements VCInterface using GitPython for branch management and commits.

Clean Architecture: Adapter layer (external system integration)
SOLID: ISP (minimal interface), DIP (implements abstraction)

Generated by ULTRATHINK (dsl-task-engineer agent) on 2025-10-04.
"""

from typing import Protocol, Dict, Any
from git import Repo, GitCommandError


class VCInterface(Protocol):
    """Minimal interface for version control operations, following ISP."""

    def create_branch(self, branch_name: str) -> None:
        """Create a new branch."""
        ...

    def commit_changes(self, message: str, files: list[str]) -> None:
        """Atomically commit specified files."""
        ...


class GitAdapter:
    """Adapter for Git version control, implementing VCInterface.

    Uses GitPython for branch creation and atomic commits.
    Config is injected via constructor for DIP.
    """

    def __init__(self, config: Dict[str, Any]) -> None:
        """Initialize with configuration (e.g., {'repo_path': '/path/to/repo'})."""
        self.config = config
        repo_path = config.get('repo_path')
        if not repo_path:
            raise ValueError("Config must include 'repo_path'")
        try:
            self.repo = Repo(repo_path)
        except Exception as e:
            raise ValueError(f"Failed to initialize Git repo at '{repo_path}': {e}") from e

    def create_branch(self, branch_name: str) -> None:
        """Create a new branch from current HEAD."""
        try:
            self.repo.git.checkout('HEAD', b=branch_name)
        except GitCommandError as e:
            raise ValueError(f"Failed to create branch '{branch_name}': {e}") from e

    def commit_changes(self, message: str, files: list[str]) -> None:
        """Add files and commit atomically."""
        try:
            self.repo.index.add(files)
            self.repo.index.commit(message)
        except GitCommandError as e:
            raise ValueError(f"Failed to commit changes: {e}") from e
