"""Logger Adapter for Structured Logging

Implements LoggingInterface using Python's standard logging module.

Clean Architecture: Adapter layer (external system integration)
SOLID: ISP (minimal interface), DIP (implements abstraction)

Generated by ULTRATHINK (dsl-task-engineer agent) on 2025-10-04.
"""

from typing import Protocol, Dict, Any
import logging


class LoggingInterface(Protocol):
    """Minimal interface for logging, following ISP."""

    def log_info(self, message: str) -> None:
        """Log an info message."""
        ...

    def log_error(self, message: str) -> None:
        """Log an error message."""
        ...


class LoggerAdapter:
    """Adapter for structured logging, implementing LoggingInterface.

    Uses standard logging module.
    Config is injected via constructor for DIP.
    """

    def __init__(self, config: Dict[str, Any]) -> None:
        """Initialize with configuration (e.g., {'level': 'INFO', 'format': '%(asctime)s - %(levelname)s - %(message)s'})."""
        self.config = config
        level = getattr(logging, config.get('level', 'INFO').upper(), logging.INFO)
        format_str = config.get('format', '%(asctime)s - %(levelname)s - %(message)s')
        logging.basicConfig(level=level, format=format_str)
        self.logger = logging.getLogger(__name__)

    def log_info(self, message: str) -> None:
        """Log an info message."""
        try:
            self.logger.info(message)
        except Exception as e:
            # Fallback if logging fails
            print(f"Logging error: {e}; Original message: {message}")

    def log_error(self, message: str) -> None:
        """Log an error message."""
        try:
            self.logger.error(message)
        except Exception as e:
            print(f"Logging error: {e}; Original message: {message}")
