"""Priority Queue Adapter for polling tasks from YAML file

Implements TaskPoller protocol to read from priorities.yaml.

Clean Architecture: Adapter layer (external data source)
SOLID: ISP (minimal interface), SRP (polling only)

Generated by ULTRATHINK (dsl-task-engineer agent) on 2025-10-04.
"""

import yaml
from pathlib import Path
from typing import Dict, List, Any
from src.priority_queue.entities import Task


class PriorityQueueAdapter:
    """
    Adapter for polling tasks from a YAML file.

    This adapter reads tasks from a priorities.yaml file, filters for open tasks,
    sorts them by priority (highest first), and returns Task entities.
    It adheres to Clean Architecture as an adapter layer, handling external data sources,
    and follows SOLID principles: SRP (single responsibility of polling and converting tasks)
    and ISP (minimal interface).
    """

    # Priority string to numeric mapping for sorting
    PRIORITY_MAP = {
        'critical': 4,
        'high': 3,
        'medium': 2,
        'low': 1
    }

    def __init__(self, config: Dict[str, str]) -> None:
        """
        Initialize the adapter with configuration.

        Args:
            config (Dict[str, str]): Configuration dictionary containing 'queue_file' key
                                     pointing to the YAML file path.

        Raises:
            KeyError: If 'queue_file' is missing from config.
        """
        if 'queue_file' not in config:
            raise KeyError("Configuration must include 'queue_file' key.")
        self.queue_file = Path(config['queue_file'])

    def poll_tasks(self) -> List[Task]:
        """
        Poll tasks from the YAML file.

        Reads the priorities.yaml file, parses it, filters for tasks with status 'open',
        sorts them by priority in descending order (highest first), and converts them to Task entities.

        Returns:
            List[Task]: List of open Task entities sorted by priority descending.

        Raises:
            FileNotFoundError: If the queue_file does not exist.
            yaml.YAMLError: If the YAML file is malformed.
            ValueError: If task data is invalid (e.g., missing required fields).
        """
        try:
            with open(self.queue_file, 'r') as file:
                data = yaml.safe_load(file)
        except FileNotFoundError:
            raise FileNotFoundError(f"Queue file '{self.queue_file}' not found.")
        except yaml.YAMLError as e:
            raise yaml.YAMLError(f"Error parsing YAML file: {e}")

        if not isinstance(data, dict) or 'priorities' not in data:
            raise ValueError("YAML file must contain 'priorities' key with list of tasks.")

        priorities_list = data['priorities']
        if not isinstance(priorities_list, list):
            raise ValueError("'priorities' must be a list of tasks.")

        open_tasks = []
        for task_dict in priorities_list:
            if not isinstance(task_dict, dict):
                raise ValueError("Each task in priorities must be a dictionary.")

            # Filter for open tasks
            if task_dict.get('status') == 'open':
                # Validate required fields
                if 'id' not in task_dict:
                    raise ValueError("Task must have 'id' field.")

                # Convert priority string to numeric for sorting
                priority_str = task_dict.get('priority', 'low').lower()
                priority_num = self.PRIORITY_MAP.get(priority_str, 1)

                # Build task with numeric priority
                task_data = {
                    'id': task_dict['id'],
                    'priority': priority_num,
                    'status': task_dict['status'],
                    'metadata': {
                        'title': task_dict.get('title', ''),
                        'effort_hours': task_dict.get('effort_hours', 0),
                        'workflow': task_dict.get('workflow', ''),
                        'claimed_by': task_dict.get('claimed_by'),
                        'priority_str': priority_str
                    }
                }
                open_tasks.append(task_data)

        # Sort by numeric priority descending (highest first)
        sorted_tasks = sorted(open_tasks, key=lambda t: t['priority'], reverse=True)

        # Convert to Task entities
        return [Task(**task) for task in sorted_tasks]
