"""Redis Adapter for Task Queue, Locking, and Deduplication

Implements shared task queue with atomic claiming for PriorityWorker.

Features:
- Task submission (LPUSH to priority queue)
- Atomic claiming (SETNX with TTL)
- Status tracking (HSET for task metadata)
- Hash-based deduplication (prevent duplicate work)
- Lock interface for coordination
- Hierarchical priority tracking (Phase 1)

Clean Architecture: Adapter layer (external system integration)
SOLID: ISP (minimal interface), DIP (implements abstraction)

Generated by ULTRATHINK (dsl-task-engineer agent) on 2025-10-04.
Enhanced with task queue functionality on 2025-10-04.
Enhanced with hierarchical priority system (Phase 1) on 2025-10-04.
"""

from typing import Protocol, Dict, Any, Optional, List
import hashlib
import json
import redis
import sys
from pathlib import Path

# Add src to path for Priority entity import
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from src.priority_queue.entities import Priority


class LockInterface(Protocol):
    """Minimal interface for locking operations, following ISP."""

    def acquire_lock(self, key: str, ttl_seconds: int) -> bool:
        """Attempt to acquire a lock with TTL."""
        ...

    def release_lock(self, key: str) -> bool:
        """Release a lock."""
        ...


class RedisAdapter:
    """Adapter for Redis-based task queue, locking, and caching.

    Implements:
    - Task queue operations (submit, claim, poll)
    - Atomic locking (SET NX PX for claiming)
    - Status tracking (HSET for task metadata)
    - Deduplication (hash-based detection)

    Config is injected via constructor for DIP.
    """

    QUEUE_KEY = "priority_queue"
    STATUS_PREFIX = "task_status:"
    CLAIM_PREFIX = "task_claim:"
    HASH_PREFIX = "task_hash:"
    PRIORITY_PREFIX = "priority:"  # Phase 1: Priority storage
    PRIORITY_CHILDREN_PREFIX = "priority_children:"  # Phase 1: Parent-child index

    def __init__(self, config: Dict[str, Any]) -> None:
        """Initialize with configuration (e.g., {'host': 'localhost', 'port': 6379, 'db': 0, 'lock_ttl': 3600})."""
        self.config = config
        self.lock_ttl = config.get('lock_ttl', 3600)  # Default 1 hour TTL
        try:
            self.client = redis.Redis(
                host=config.get('host', 'localhost'),
                port=config.get('port', 6379),
                db=config.get('db', 0),
                decode_responses=True  # Auto-decode bytes to strings
            )
            self.client.ping()  # Test connection
        except redis.ConnectionError as e:
            raise ValueError(f"Failed to connect to Redis: {e}") from e
        except Exception as e:
            raise ValueError(f"Redis initialization error: {e}") from e

    def _compute_hash(self, task_description: str) -> str:
        """Compute SHA256 hash for deduplication."""
        return hashlib.sha256(task_description.encode()).hexdigest()

    def submit_task(
        self,
        task_id: str,
        priority: int,
        description: str,
        metadata: Dict[str, Any],
        parent_priority_id: Optional[str] = None,
        spawned_by: str = "user"
    ) -> bool:
        """Submit task to priority queue with deduplication check and Phase 1 parent tracking.

        Args:
            task_id: Unique task identifier
            priority: Task priority (higher = more urgent)
            description: Task description for deduplication
            metadata: Additional task metadata
            parent_priority_id: Optional parent priority ID for hierarchical tracking
            spawned_by: Task source (user, ultrathink, analysis) - default: user

        Returns:
            True if submitted, False if duplicate detected
        """
        try:
            # Check for duplicate via hash
            task_hash = self._compute_hash(description)
            hash_key = f"{self.HASH_PREFIX}{task_hash}"

            if self.client.exists(hash_key):
                return False  # Duplicate detected

            # Store hash with task_id reference (TTL = 24h)
            self.client.setex(hash_key, 86400, task_id)

            # Phase 1: Get parent context hash if parent provided
            parent_context_hash = None
            if parent_priority_id:
                parent_priority = self.get_priority(parent_priority_id)
                if parent_priority:
                    parent_context_hash = parent_priority.context_hash
                else:
                    raise ValueError(f"Parent priority {parent_priority_id} not found")

            # Store task metadata with Phase 1 fields
            task_data = {
                'id': task_id,
                'priority': priority,
                'description': description,
                'metadata': json.dumps(metadata),
                'status': 'open',
                'parent_priority_id': parent_priority_id or '',  # Empty string for None
                'parent_context_hash': parent_context_hash or '',
                'is_stale': 'false',  # Redis stores as string
                'spawned_by': spawned_by
            }
            status_key = f"{self.STATUS_PREFIX}{task_id}"
            self.client.hset(status_key, mapping=task_data)

            # Phase 1: Link task to parent priority
            if parent_priority_id:
                self.link_task_to_priority(task_id, parent_priority_id)

            # Add to priority queue (LPUSH for FIFO, priority handled externally)
            self.client.lpush(self.QUEUE_KEY, task_id)

            return True
        except redis.RedisError as e:
            raise ValueError(f"Failed to submit task {task_id}: {e}") from e

    def poll_tasks(self, status: str = 'open', limit: int = 10, include_stale: bool = False) -> List[Dict[str, Any]]:
        """Poll tasks from queue with specific status.

        Args:
            status: Filter by task status (default: 'open')
            limit: Maximum tasks to return
            include_stale: Include stale tasks (default: False, filters them out)

        Returns:
            List of task dictionaries with Phase 1 fields
        """
        try:
            # Get task IDs from queue (LRANGE for peeking without removal)
            task_ids = self.client.lrange(self.QUEUE_KEY, 0, limit - 1)

            tasks = []
            for task_id in task_ids:
                status_key = f"{self.STATUS_PREFIX}{task_id}"
                task_data = self.client.hgetall(status_key)

                if not task_data or task_data.get('status') != status:
                    continue

                # Phase 2: Filter out stale tasks unless explicitly requested
                is_stale = task_data.get('is_stale', 'false') == 'true'
                if is_stale and not include_stale:
                    continue

                tasks.append({
                    'id': task_data['id'],
                    'priority': int(task_data['priority']),
                    'description': task_data.get('description', ''),
                    'metadata': json.loads(task_data['metadata']),
                    'status': task_data['status'],
                    # Phase 1 fields
                    'parent_priority_id': task_data.get('parent_priority_id', ''),
                    'parent_context_hash': task_data.get('parent_context_hash', ''),
                    'is_stale': is_stale,
                    'spawned_by': task_data.get('spawned_by', 'user')
                })

            return tasks
        except redis.RedisError as e:
            raise ValueError(f"Failed to poll tasks: {e}") from e

    def claim_task(self, task_id: str, claimant: str) -> bool:
        """Atomically claim a task using SETNX.

        Args:
            task_id: Task to claim
            claimant: Identifier of claiming worker

        Returns:
            True if claimed successfully
        """
        try:
            claim_key = f"{self.CLAIM_PREFIX}{task_id}"

            # Atomic claim with TTL
            claimed = self.client.set(claim_key, claimant, nx=True, ex=self.lock_ttl)

            if claimed:
                # Update status to claimed
                status_key = f"{self.STATUS_PREFIX}{task_id}"
                self.client.hset(status_key, 'status', 'claimed')

                # Remove from queue (LREM to remove by value)
                self.client.lrem(self.QUEUE_KEY, 1, task_id)

            return bool(claimed)
        except redis.RedisError as e:
            raise ValueError(f"Failed to claim task {task_id}: {e}") from e

    def update_status(self, task_id: str, new_status: str) -> None:
        """Update task status.

        Args:
            task_id: Task to update
            new_status: New status (open/claimed/in_progress/completed/failed)
        """
        try:
            status_key = f"{self.STATUS_PREFIX}{task_id}"
            self.client.hset(status_key, 'status', new_status)
        except redis.RedisError as e:
            raise ValueError(f"Failed to update status for task {task_id}: {e}") from e

    def release_claim(self, task_id: str) -> None:
        """Release claim on a task (for failures or timeouts)."""
        try:
            claim_key = f"{self.CLAIM_PREFIX}{task_id}"
            self.client.delete(claim_key)

            # Re-add to queue if not completed/failed
            status_key = f"{self.STATUS_PREFIX}{task_id}"
            status = self.client.hget(status_key, 'status')

            if status not in ['completed', 'failed']:
                self.client.hset(status_key, 'status', 'open')
                self.client.lpush(self.QUEUE_KEY, task_id)
        except redis.RedisError as e:
            raise ValueError(f"Failed to release claim for task {task_id}: {e}") from e

    # Legacy lock interface (for use cases)
    def acquire_lock(self, key: str, ttl_seconds: int) -> bool:
        """Acquire a lock using SET NX PX. Returns True if acquired."""
        try:
            return bool(self.client.set(key, 'locked', nx=True, px=ttl_seconds * 1000))
        except redis.RedisError as e:
            raise ValueError(f"Failed to acquire lock for key '{key}': {e}") from e

    def release_lock(self, key: str) -> bool:
        """Release a lock by deleting the key. Returns True if deleted."""
        try:
            return bool(self.client.delete(key))
        except redis.RedisError as e:
            raise ValueError(f"Failed to release lock for key '{key}': {e}") from e

    async def lock(self, resource: str) -> bool:
        """Async wrapper for acquire_lock, matching use case LockInterface."""
        return self.acquire_lock(resource, ttl_seconds=300)  # 5 minute TTL

    async def unlock(self, resource: str) -> None:
        """Async wrapper for release_lock, matching use case LockInterface."""
        self.release_lock(resource)

    # Phase 1: Priority CRUD Operations
    def create_priority(self, priority: Priority) -> bool:
        """Create a new priority in Redis.

        Args:
            priority: Priority entity to store

        Returns:
            True if created, False if already exists
        """
        try:
            priority_key = f"{self.PRIORITY_PREFIX}{priority.id}"

            # Check if already exists
            if self.client.exists(priority_key):
                return False

            # Store priority as hash
            self.client.hset(priority_key, mapping=priority.to_dict())

            return True
        except redis.RedisError as e:
            raise ValueError(f"Failed to create priority {priority.id}: {e}") from e

    def get_priority(self, priority_id: str) -> Optional[Priority]:
        """Retrieve priority by ID.

        Args:
            priority_id: Priority ID to retrieve

        Returns:
            Priority entity if found, None otherwise
        """
        try:
            priority_key = f"{self.PRIORITY_PREFIX}{priority_id}"
            priority_data = self.client.hgetall(priority_key)

            if not priority_data:
                return None

            return Priority.from_dict(priority_data)
        except redis.RedisError as e:
            raise ValueError(f"Failed to get priority {priority_id}: {e}") from e

    def update_priority(self, priority: Priority) -> bool:
        """Update an existing priority (context changes trigger staleness detection).

        Args:
            priority: Priority entity with updated fields

        Returns:
            True if updated, False if not found
        """
        try:
            priority_key = f"{self.PRIORITY_PREFIX}{priority.id}"

            # Check if exists
            if not self.client.exists(priority_key):
                return False

            # Phase 2: Check if context changed (triggers staleness)
            old_priority_data = self.client.hgetall(priority_key)
            old_context_hash = old_priority_data.get('context_hash')
            context_changed = old_context_hash and old_context_hash != priority.context_hash

            # Update priority (context_hash will be recomputed)
            self.client.hset(priority_key, mapping=priority.to_dict())

            # Phase 2: Mark children stale when context changes
            if context_changed:
                self.mark_children_stale(priority.id)

            return True
        except redis.RedisError as e:
            raise ValueError(f"Failed to update priority {priority.id}: {e}") from e

    def delete_priority(self, priority_id: str) -> bool:
        """Delete a priority and its child task index.

        Args:
            priority_id: Priority ID to delete

        Returns:
            True if deleted, False if not found
        """
        try:
            priority_key = f"{self.PRIORITY_PREFIX}{priority_id}"
            children_key = f"{self.PRIORITY_CHILDREN_PREFIX}{priority_id}"

            # Delete priority
            deleted = self.client.delete(priority_key)

            # Delete children index
            self.client.delete(children_key)

            return bool(deleted)
        except redis.RedisError as e:
            raise ValueError(f"Failed to delete priority {priority_id}: {e}") from e

    def link_task_to_priority(self, task_id: str, priority_id: str) -> None:
        """Link a task to its parent priority (parent-child index).

        Args:
            task_id: Task ID
            priority_id: Parent priority ID
        """
        try:
            children_key = f"{self.PRIORITY_CHILDREN_PREFIX}{priority_id}"
            self.client.sadd(children_key, task_id)
        except redis.RedisError as e:
            raise ValueError(f"Failed to link task {task_id} to priority {priority_id}: {e}") from e

    def get_priority_children(self, priority_id: str) -> List[str]:
        """Get all child task IDs for a priority.

        Args:
            priority_id: Priority ID

        Returns:
            List of task IDs linked to this priority
        """
        try:
            children_key = f"{self.PRIORITY_CHILDREN_PREFIX}{priority_id}"
            return list(self.client.smembers(children_key))
        except redis.RedisError as e:
            raise ValueError(f"Failed to get children for priority {priority_id}: {e}") from e

    def mark_children_stale(self, priority_id: str) -> int:
        """Mark all child tasks as stale when parent priority context changes.

        Phase 2: Staleness detection on context change.

        Args:
            priority_id: Priority ID whose children should be marked stale

        Returns:
            Number of tasks marked stale
        """
        try:
            # Get all child task IDs
            children_key = f"{self.PRIORITY_CHILDREN_PREFIX}{priority_id}"
            child_task_ids = self.client.smembers(children_key)

            marked_count = 0
            for task_id in child_task_ids:
                status_key = f"{self.STATUS_PREFIX}{task_id}"

                # Check if task exists and is not already completed/failed
                task_data = self.client.hgetall(status_key)
                if not task_data:
                    continue

                current_status = task_data.get('status', '')
                if current_status in ['completed', 'failed', 'stale']:
                    continue  # Don't mark completed/failed/already-stale tasks

                # Mark as stale
                self.client.hset(status_key, 'is_stale', 'true')
                self.client.hset(status_key, 'status', 'stale')
                marked_count += 1

            return marked_count
        except redis.RedisError as e:
            raise ValueError(f"Failed to mark children stale for priority {priority_id}: {e}") from e
