"""Redis Adapter for Task Queue, Locking, and Deduplication

Implements shared task queue with atomic claiming for PriorityWorker.

Features:
- Task submission (LPUSH to priority queue)
- Atomic claiming (SETNX with TTL)
- Status tracking (HSET for task metadata)
- Hash-based deduplication (prevent duplicate work)
- Lock interface for coordination

Clean Architecture: Adapter layer (external system integration)
SOLID: ISP (minimal interface), DIP (implements abstraction)

Generated by ULTRATHINK (dsl-task-engineer agent) on 2025-10-04.
Enhanced with task queue functionality on 2025-10-04.
"""

from typing import Protocol, Dict, Any, Optional, List
import hashlib
import json
import redis


class LockInterface(Protocol):
    """Minimal interface for locking operations, following ISP."""

    def acquire_lock(self, key: str, ttl_seconds: int) -> bool:
        """Attempt to acquire a lock with TTL."""
        ...

    def release_lock(self, key: str) -> bool:
        """Release a lock."""
        ...


class RedisAdapter:
    """Adapter for Redis-based task queue, locking, and caching.

    Implements:
    - Task queue operations (submit, claim, poll)
    - Atomic locking (SET NX PX for claiming)
    - Status tracking (HSET for task metadata)
    - Deduplication (hash-based detection)

    Config is injected via constructor for DIP.
    """

    QUEUE_KEY = "priority_queue"
    STATUS_PREFIX = "task_status:"
    CLAIM_PREFIX = "task_claim:"
    HASH_PREFIX = "task_hash:"

    def __init__(self, config: Dict[str, Any]) -> None:
        """Initialize with configuration (e.g., {'host': 'localhost', 'port': 6379, 'db': 0, 'lock_ttl': 3600})."""
        self.config = config
        self.lock_ttl = config.get('lock_ttl', 3600)  # Default 1 hour TTL
        try:
            self.client = redis.Redis(
                host=config.get('host', 'localhost'),
                port=config.get('port', 6379),
                db=config.get('db', 0),
                decode_responses=True  # Auto-decode bytes to strings
            )
            self.client.ping()  # Test connection
        except redis.ConnectionError as e:
            raise ValueError(f"Failed to connect to Redis: {e}") from e
        except Exception as e:
            raise ValueError(f"Redis initialization error: {e}") from e

    def _compute_hash(self, task_description: str) -> str:
        """Compute SHA256 hash for deduplication."""
        return hashlib.sha256(task_description.encode()).hexdigest()

    def submit_task(self, task_id: str, priority: int, description: str, metadata: Dict[str, Any]) -> bool:
        """Submit task to priority queue with deduplication check.

        Args:
            task_id: Unique task identifier
            priority: Task priority (higher = more urgent)
            description: Task description for deduplication
            metadata: Additional task metadata

        Returns:
            True if submitted, False if duplicate detected
        """
        try:
            # Check for duplicate via hash
            task_hash = self._compute_hash(description)
            hash_key = f"{self.HASH_PREFIX}{task_hash}"

            if self.client.exists(hash_key):
                return False  # Duplicate detected

            # Store hash with task_id reference (TTL = 24h)
            self.client.setex(hash_key, 86400, task_id)

            # Store task metadata
            task_data = {
                'id': task_id,
                'priority': priority,
                'description': description,
                'metadata': json.dumps(metadata),
                'status': 'open'
            }
            status_key = f"{self.STATUS_PREFIX}{task_id}"
            self.client.hset(status_key, mapping=task_data)

            # Add to priority queue (LPUSH for FIFO, priority handled externally)
            self.client.lpush(self.QUEUE_KEY, task_id)

            return True
        except redis.RedisError as e:
            raise ValueError(f"Failed to submit task {task_id}: {e}") from e

    def poll_tasks(self, status: str = 'open', limit: int = 10) -> List[Dict[str, Any]]:
        """Poll tasks from queue with specific status.

        Args:
            status: Filter by task status (default: 'open')
            limit: Maximum tasks to return

        Returns:
            List of task dictionaries
        """
        try:
            # Get task IDs from queue (LRANGE for peeking without removal)
            task_ids = self.client.lrange(self.QUEUE_KEY, 0, limit - 1)

            tasks = []
            for task_id in task_ids:
                status_key = f"{self.STATUS_PREFIX}{task_id}"
                task_data = self.client.hgetall(status_key)

                if task_data and task_data.get('status') == status:
                    tasks.append({
                        'id': task_data['id'],
                        'priority': int(task_data['priority']),
                        'description': task_data['description'],
                        'metadata': json.loads(task_data['metadata']),
                        'status': task_data['status']
                    })

            return tasks
        except redis.RedisError as e:
            raise ValueError(f"Failed to poll tasks: {e}") from e

    def claim_task(self, task_id: str, claimant: str) -> bool:
        """Atomically claim a task using SETNX.

        Args:
            task_id: Task to claim
            claimant: Identifier of claiming worker

        Returns:
            True if claimed successfully
        """
        try:
            claim_key = f"{self.CLAIM_PREFIX}{task_id}"

            # Atomic claim with TTL
            claimed = self.client.set(claim_key, claimant, nx=True, ex=self.lock_ttl)

            if claimed:
                # Update status to claimed
                status_key = f"{self.STATUS_PREFIX}{task_id}"
                self.client.hset(status_key, 'status', 'claimed')

                # Remove from queue (LREM to remove by value)
                self.client.lrem(self.QUEUE_KEY, 1, task_id)

            return bool(claimed)
        except redis.RedisError as e:
            raise ValueError(f"Failed to claim task {task_id}: {e}") from e

    def update_status(self, task_id: str, new_status: str) -> None:
        """Update task status.

        Args:
            task_id: Task to update
            new_status: New status (open/claimed/in_progress/completed/failed)
        """
        try:
            status_key = f"{self.STATUS_PREFIX}{task_id}"
            self.client.hset(status_key, 'status', new_status)
        except redis.RedisError as e:
            raise ValueError(f"Failed to update status for task {task_id}: {e}") from e

    def release_claim(self, task_id: str) -> None:
        """Release claim on a task (for failures or timeouts)."""
        try:
            claim_key = f"{self.CLAIM_PREFIX}{task_id}"
            self.client.delete(claim_key)

            # Re-add to queue if not completed/failed
            status_key = f"{self.STATUS_PREFIX}{task_id}"
            status = self.client.hget(status_key, 'status')

            if status not in ['completed', 'failed']:
                self.client.hset(status_key, 'status', 'open')
                self.client.lpush(self.QUEUE_KEY, task_id)
        except redis.RedisError as e:
            raise ValueError(f"Failed to release claim for task {task_id}: {e}") from e

    # Legacy lock interface (for use cases)
    def acquire_lock(self, key: str, ttl_seconds: int) -> bool:
        """Acquire a lock using SET NX PX. Returns True if acquired."""
        try:
            return bool(self.client.set(key, 'locked', nx=True, px=ttl_seconds * 1000))
        except redis.RedisError as e:
            raise ValueError(f"Failed to acquire lock for key '{key}': {e}") from e

    def release_lock(self, key: str) -> bool:
        """Release a lock by deleting the key. Returns True if deleted."""
        try:
            return bool(self.client.delete(key))
        except redis.RedisError as e:
            raise ValueError(f"Failed to release lock for key '{key}': {e}") from e

    async def lock(self, resource: str) -> bool:
        """Async wrapper for acquire_lock, matching use case LockInterface."""
        return self.acquire_lock(resource, ttl_seconds=300)  # 5 minute TTL

    async def unlock(self, resource: str) -> None:
        """Async wrapper for release_lock, matching use case LockInterface."""
        self.release_lock(resource)
