"""Redis Adapter for Locking and Caching

Implements LockInterface using Redis SET with NX PX for atomic claiming.

Clean Architecture: Adapter layer (external system integration)
SOLID: ISP (minimal interface), DIP (implements abstraction)

Generated by ULTRATHINK (dsl-task-engineer agent) on 2025-10-04.
"""

from typing import Protocol, Dict, Any
import redis


class LockInterface(Protocol):
    """Minimal interface for locking operations, following ISP."""

    def acquire_lock(self, key: str, ttl_seconds: int) -> bool:
        """Attempt to acquire a lock with TTL."""
        ...

    def release_lock(self, key: str) -> bool:
        """Release a lock."""
        ...


class RedisAdapter:
    """Adapter for Redis-based locking and caching, implementing LockInterface.

    Uses redis library for SET with NX PX (TTL) to claim/lock resources.
    Config is injected via constructor for DIP.
    """

    def __init__(self, config: Dict[str, Any]) -> None:
        """Initialize with configuration (e.g., {'host': 'localhost', 'port': 6379, 'db': 0})."""
        self.config = config
        try:
            self.client = redis.Redis(**config)
            self.client.ping()  # Test connection
        except redis.ConnectionError as e:
            raise ValueError(f"Failed to connect to Redis: {e}") from e
        except Exception as e:
            raise ValueError(f"Redis initialization error: {e}") from e

    def acquire_lock(self, key: str, ttl_seconds: int) -> bool:
        """Acquire a lock using SET NX PX. Returns True if acquired."""
        try:
            return bool(self.client.set(key, 'locked', nx=True, px=ttl_seconds * 1000))
        except redis.RedisError as e:
            raise ValueError(f"Failed to acquire lock for key '{key}': {e}") from e

    def release_lock(self, key: str) -> bool:
        """Release a lock by deleting the key. Returns True if deleted."""
        try:
            return bool(self.client.delete(key))
        except redis.RedisError as e:
            raise ValueError(f"Failed to release lock for key '{key}': {e}") from e

    async def lock(self, resource: str) -> bool:
        """Async wrapper for acquire_lock, matching use case LockInterface."""
        return self.acquire_lock(resource, ttl_seconds=300)  # 5 minute TTL

    async def unlock(self, resource: str) -> None:
        """Async wrapper for release_lock, matching use case LockInterface."""
        self.release_lock(resource)
