"""
Execute architectural blueprint query with Qwen3-Next-80B-Thinking model.

This script queries the premium reasoning model with maximum context and tokens
to generate a comprehensive architectural blueprint for the Agentic Project Builder.
"""

import asyncio
import sys
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).parent))

from src.adapters.llm.qwen3_next_80b_thinking_adapter import Qwen3Next80BThinkingAdapter
from src.interfaces import LLMConfig


async def main():
    print("="*80)
    print("ARCHITECTURAL BLUEPRINT GENERATION")
    print("="*80)
    print()
    print("Model: Qwen3-Next-80B-A3B-Thinking")
    print("Max Tokens: 81,920 (maximum for complex architectural tasks)")
    print("Temperature: 0.6 (balanced reasoning)")
    print("Timeout: 600s (10 minutes)")
    print()

    # Read context and query
    print("Loading context and query documents...")
    context = Path("PROJECT_BUILDER_CONTEXT.md").read_text()
    query = Path("PROJECT_BUILDER_QUERY.md").read_text()

    print(f"Context size: {len(context)} characters (~{len(context.split())} words)")
    print(f"Query size: {len(query)} characters (~{len(query.split())} words)")
    print()

    # Combine into comprehensive prompt
    full_prompt = f"""# CONTEXT DOCUMENT

{context}

---

# ARCHITECTURAL QUERY

{query}
"""

    print(f"Total prompt size: {len(full_prompt)} characters (~{len(full_prompt.split())} words)")
    print()
    print("Executing query with thinking model...")
    print("(This may take 2-5 minutes for comprehensive analysis)")
    print()

    # Initialize adapter
    adapter = Qwen3Next80BThinkingAdapter(
        timeout=600  # 10 minutes for comprehensive architectural work
    )

    # Create config with maximum tokens for complex tasks
    config = LLMConfig(
        temperature=0.6,
        max_tokens=81920  # Maximum for complex math/code/architecture tasks
    )

    # Execute with thinking response
    try:
        response = adapter.generate_with_thinking(
            messages=[{"role": "user", "content": full_prompt}],
            config=config
        )

        print("="*80)
        print("RESPONSE RECEIVED")
        print("="*80)
        print()
        print(f"Thinking process: {len(response.thinking)} characters ({len(response.thinking.split())} words)")
        print(f"Final blueprint: {len(response.answer)} characters ({len(response.answer.split())} words)")
        print(f"Total response: {len(response.raw)} characters ({len(response.raw.split())} words)")
        print(f"Thinking-to-answer ratio: {len(response.thinking)/len(response.answer):.2f}x")
        print()

        # Save outputs
        output_dir = Path("docs")
        output_dir.mkdir(exist_ok=True)

        # Save complete blueprint
        blueprint_path = output_dir / "AGENTIC_PROJECT_BUILDER_BLUEPRINT.md"
        with open(blueprint_path, "w") as f:
            f.write("# Agentic Project Builder - Architectural Blueprint\n\n")
            f.write("**Generated by**: Qwen3-Next-80B-A3B-Thinking\n")
            f.write("**Date**: 2025-10-06\n")
            f.write(f"**Thinking Process**: {len(response.thinking)} chars ({len(response.thinking.split())} words)\n")
            f.write(f"**Blueprint**: {len(response.answer)} chars ({len(response.answer.split())} words)\n")
            f.write(f"**Ratio**: {len(response.thinking)/len(response.answer):.2f}x (extensive reasoning)\n\n")
            f.write("---\n\n")
            f.write("## Thinking Process\n\n")
            f.write(response.thinking)
            f.write("\n\n---\n\n")
            f.write("## Architectural Blueprint\n\n")
            f.write(response.answer)

        print(f"✓ Blueprint saved to: {blueprint_path}")
        print()

        # Save thinking process separately for analysis
        thinking_path = output_dir / "BLUEPRINT_THINKING_PROCESS.md"
        with open(thinking_path, "w") as f:
            f.write("# Architectural Blueprint - Thinking Process\n\n")
            f.write("**Model**: Qwen3-Next-80B-A3B-Thinking\n")
            f.write(f"**Size**: {len(response.thinking)} characters ({len(response.thinking.split())} words)\n\n")
            f.write("---\n\n")
            f.write(response.thinking)

        print(f"✓ Thinking process saved to: {thinking_path}")
        print()

        print("="*80)
        print("GENERATION COMPLETE")
        print("="*80)
        print()
        print(f"Blueprint available at: {blueprint_path}")
        print()

        # Show preview of blueprint
        print("=" * 80)
        print("BLUEPRINT PREVIEW (first 1000 characters)")
        print("="*80)
        print(response.answer[:1000])
        print("...")
        print()

        return True

    except Exception as e:
        print(f"ERROR: {e}")
        import traceback
        traceback.print_exc()
        return False


if __name__ == "__main__":
    success = asyncio.run(main())
    sys.exit(0 if success else 1)
