"""GeneratedTask Entity.

Represents a task generated by Claude based on current context.
Contains task specification, rationale, and metadata.

Clean Architecture: Core entity (immutable, no dependencies)
SOLID: SRP - single responsibility for task representation
"""

from dataclasses import dataclass
from typing import Dict, List, Optional, Any
from datetime import datetime


@dataclass(frozen=True)
class GeneratedTask:
    """
    Task generated by Claude orchestrator based on current context.

    Contains full task specification including:
    - What to do (instruction)
    - Why (rationale)
    - How long (estimated_minutes)
    - Which goal (goal_id)

    Example:
        task = GeneratedTask.create(
            id="task-abc123",
            instruction="Add unit tests for parser.py:150-200 to improve coverage",
            rationale="Coverage analysis shows parser.py:150-200 uncovered (0%). Goal: 95% coverage.",
            goal_id="test-coverage-95",
            estimated_minutes=30,
            priority="P1",
        )
    """

    # Identity
    id: str
    generated_at: datetime

    # Task specification
    instruction: str  # Clear instruction for worker
    rationale: str  # Why this task now (context-aware)
    goal_id: str  # Which goal this contributes to

    # Planning
    estimated_minutes: int  # Expected completion time
    priority: str  # P0, P1, P2, P3
    complexity: str  # "low", "medium", "high"

    # Context
    related_files: List[str]  # Files this task will modify
    dependencies: List[str]  # Other task IDs this depends on

    # Metadata
    generator_version: str = "1.0"
    confidence_score: float = 0.8  # 0.0-1.0, Claude's confidence

    @staticmethod
    def create(
        id: str,
        instruction: str,
        rationale: str,
        goal_id: str,
        estimated_minutes: int,
        priority: str,
        complexity: str = "medium",
        related_files: Optional[List[str]] = None,
        dependencies: Optional[List[str]] = None,
        confidence_score: float = 0.8,
    ) -> "GeneratedTask":
        """Factory method to create GeneratedTask."""
        return GeneratedTask(
            id=id,
            generated_at=datetime.now(),
            instruction=instruction,
            rationale=rationale,
            goal_id=goal_id,
            estimated_minutes=estimated_minutes,
            priority=priority,
            complexity=complexity,
            related_files=related_files or [],
            dependencies=dependencies or [],
            confidence_score=confidence_score,
        )

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "id": self.id,
            "generated_at": self.generated_at.isoformat(),
            "instruction": self.instruction,
            "rationale": self.rationale,
            "goal_id": self.goal_id,
            "estimated_minutes": self.estimated_minutes,
            "priority": self.priority,
            "complexity": self.complexity,
            "related_files": self.related_files,
            "dependencies": self.dependencies,
            "generator_version": self.generator_version,
            "confidence_score": self.confidence_score,
        }
