"""Priority Queue Entities Layer

Core data models with no external dependencies.

Clean Architecture: Entities layer (innermost circle)
SOLID: SRP (single responsibility per entity)

Generated by ULTRATHINK (backend-lead agent) on 2025-10-04.
Enhanced with hierarchical priority system on 2025-10-04.
"""

import hashlib
from dataclasses import dataclass, field
from typing import Any, Dict, Optional


@dataclass
class Priority:
    """
    Priority (parent) entity for hierarchical task tracking.

    Priorities represent top-level goals with context that can change.
    Tasks are spawned from priorities and track the parent context hash
    to detect staleness when the priority context changes.

    Attributes:
        id: Unique priority identifier (e.g., "autonomous-container")
        title: Human-readable priority title
        context: Current state, goals, and constraints
        status: Priority status (active, paused, abandoned, completed)
        context_hash: SHA256 hash of context for staleness detection (auto-computed)
    """
    id: str
    title: str
    context: str
    status: str
    context_hash: str = field(init=False)

    def __post_init__(self):
        """Auto-compute context hash after initialization."""
        self.context_hash = hashlib.sha256(self.context.encode()).hexdigest()

    def is_valid_status(self) -> bool:
        """Validate priority status."""
        allowed_statuses = frozenset({"active", "paused", "abandoned", "completed"})
        return self.status in allowed_statuses

    def to_dict(self) -> Dict[str, Any]:
        """Serialize priority to dictionary for Redis storage."""
        return {
            'id': self.id,
            'title': self.title,
            'context': self.context,
            'status': self.status,
            'context_hash': self.context_hash
        }

    @classmethod
    def from_dict(cls, data: dict) -> 'Priority':
        """Deserialize priority from dictionary (Redis retrieval)."""
        p = cls(
            id=data['id'],
            title=data['title'],
            context=data['context'],
            status=data['status']
        )
        # Preserve context_hash if stored, otherwise __post_init__ computes it
        if 'context_hash' in data:
            object.__setattr__(p, 'context_hash', data['context_hash'])
        return p


@dataclass(frozen=True)
class Task:
    """
    Represents a task entity with immutable fields.

    Enhanced with hierarchical priority tracking (Phase 1).
    Tasks are spawned from priorities and track parent context
    for staleness detection.

    Attributes:
        id: Unique task identifier
        priority: Task priority (1-5, lower is higher priority)
        status: Task status (open, claimed, in_progress, completed, failed, stale)
        metadata: Additional task metadata
        description: Task description (Phase 1 addition)
        parent_priority_id: ID of parent priority (Phase 1 addition)
        parent_context_hash: Context hash when task was created (Phase 1)
        is_stale: Whether task is stale due to parent context change (Phase 1)
        spawned_by: Source of task creation (user, ultrathink, analysis) (Phase 1)
    """
    id: str
    priority: int
    status: str
    metadata: Dict[str, Any]
    description: str = ""  # Backward compatible default
    parent_priority_id: Optional[str] = None  # Phase 1: hierarchical tracking
    parent_context_hash: Optional[str] = None  # Phase 1: staleness detection
    is_stale: bool = False  # Phase 1: staleness flag
    spawned_by: str = "user"  # Phase 1: task source tracking

    def is_valid_status(self) -> bool:
        """
        Validates if the status is one of the allowed values.

        Returns:
            bool: True if status is valid, False otherwise.
        """
        allowed_statuses = frozenset({"open", "claimed", "in_progress", "completed", "failed", "stale"})
        return self.status in allowed_statuses

    def check_staleness(self, priority: Priority) -> bool:
        """
        Check if task is stale relative to parent priority.

        Args:
            priority: Parent Priority entity to check against

        Returns:
            bool: True if task's parent_context_hash doesn't match priority's context_hash
        """
        if self.parent_priority_id is None or self.parent_context_hash is None:
            return False  # Tasks without parent tracking are never stale
        if self.parent_priority_id != priority.id:
            raise ValueError(f"Priority ID mismatch: task.parent_priority_id={self.parent_priority_id}, priority.id={priority.id}")
        return self.parent_context_hash != priority.context_hash


@dataclass(frozen=True)
class Metrics:
    """
    Represents a metrics entity with immutable fields.

    This entity encapsulates metrics data and provides validation for its values,
    adhering to SRP by focusing solely on metrics-related attributes and checks.
    """
    throughput: float  # tasks/hour
    latency: float     # seconds
    success_rate: float  # float between 0.0 and 1.0

    def is_valid_success_rate(self) -> bool:
        """
        Validates if the success_rate is within the expected range [0.0, 1.0].

        Returns:
            bool: True if success_rate is valid, False otherwise.
        """
        return 0.0 <= self.success_rate <= 1.0
