"""Priority Queue Entities Layer

Core data models with no external dependencies.

Clean Architecture: Entities layer (innermost circle)
SOLID: SRP (single responsibility per entity)

Generated by ULTRATHINK (backend-lead agent) on 2025-10-04.
"""

from dataclasses import dataclass
from typing import Any, Dict


@dataclass(frozen=True)
class Task:
    """
    Represents a task entity with immutable fields.

    This entity encapsulates task data and provides validation for its state,
    adhering to SRP by focusing solely on task-related attributes and checks.
    """
    id: str
    priority: int
    status: str
    metadata: Dict[str, Any]

    def is_valid_status(self) -> bool:
        """
        Validates if the status is one of the allowed values.

        Returns:
            bool: True if status is valid, False otherwise.
        """
        allowed_statuses = frozenset({"open", "claimed", "in_progress", "completed", "failed"})
        return self.status in allowed_statuses


@dataclass(frozen=True)
class Metrics:
    """
    Represents a metrics entity with immutable fields.

    This entity encapsulates metrics data and provides validation for its values,
    adhering to SRP by focusing solely on metrics-related attributes and checks.
    """
    throughput: float  # tasks/hour
    latency: float     # seconds
    success_rate: float  # float between 0.0 and 1.0

    def is_valid_success_rate(self) -> bool:
        """
        Validates if the success_rate is within the expected range [0.0, 1.0].

        Returns:
            bool: True if success_rate is valid, False otherwise.
        """
        return 0.0 <= self.success_rate <= 1.0
