"""Priority Worker Factory

Factory pattern for creating PriorityWorker with all dependencies wired.

Clean Architecture: Factory (outermost layer, wiring)
SOLID: DIP (creates and wires abstractions)

Generated by ULTRATHINK (backend-lead agent) on 2025-10-04, refined for actual components.
"""

import yaml
from pathlib import Path
from typing import Dict, Any

# Import actual generated components
from src.priority_queue.entities import Task, Metrics
from src.priority_queue.use_cases import (
    ClaimTaskUseCase,
    ExecuteWorkflowUseCase,
    ManageBranchesUseCase,
    HandleErrorsUseCase,
    UpdateStatusUseCase,
    TrackMetricsUseCase,
    ShutdownUseCase
)
from src.priority_queue.adapters.redis_adapter import RedisAdapter
from src.priority_queue.adapters.git_adapter import GitAdapter
from src.priority_queue.adapters.cli_executor_adapter import CLITaskExecutorAdapter
from src.priority_queue.adapters.logger_adapter import LoggerAdapter
# Phase 1: Removed PriorityQueueAdapter - now using RedisAdapter for task polling

# Import PriorityWorker orchestrator
import sys
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'scripts'))
from priority_worker import PriorityWorker


class PriorityWorkerFactory:
    """
    Factory for creating fully-wired PriorityWorker instances.

    Implements dependency injection by:
    1. Loading configuration from YAML
    2. Creating adapter instances with config
    3. Creating use case instances with adapters
    4. Creating protocol adapters to bridge use cases to PriorityWorker protocols
    5. Creating PriorityWorker with all dependencies

    Example:
        factory = PriorityWorkerFactory()
        worker = factory.create_from_config('config/priority_worker.yaml')
        await worker.run()
    """

    # Protocol adapter classes to bridge use cases to PriorityWorker protocol interfaces
    class TaskPollerAdapter:
        """Adapts RedisAdapter to TaskPoller protocol (Phase 1: Redis queue polling)."""
        def __init__(self, redis_adapter):
            self.redis_adapter = redis_adapter

        def poll_tasks(self):
            """Poll tasks from Redis queue (replaces YAML-based polling)."""
            # RedisAdapter.poll_tasks() returns dicts directly - no conversion needed
            tasks = self.redis_adapter.poll_tasks(status='open', limit=50)
            # Add metadata fields to top level for compatibility with PriorityWorker
            return [
                {
                    'id': task['id'],
                    'priority': task['priority'],
                    'status': task['status'],
                    'description': task.get('description', ''),
                    **task.get('metadata', {})
                }
                for task in tasks
            ]

    class TaskClaimerAdapter:
        """Adapts ClaimTaskUseCase to TaskClaimer protocol."""
        def __init__(self, use_case):
            self.use_case = use_case

        async def claim_task(self, task_dict):
            """Claim task by converting dict to Task entity with Phase 1 fields."""
            # Extract Phase 1 fields from dict
            phase1_fields = ['description', 'parent_priority_id', 'parent_context_hash', 'is_stale', 'spawned_by']
            metadata_keys = [k for k in task_dict.keys() if k not in ['id', 'priority', 'status'] + phase1_fields]

            task = Task(
                id=task_dict['id'],
                priority=task_dict.get('priority', 1),
                status=task_dict.get('status', 'open'),
                metadata={k: task_dict[k] for k in metadata_keys},
                description=task_dict.get('description', ''),
                parent_priority_id=task_dict.get('parent_priority_id'),
                parent_context_hash=task_dict.get('parent_context_hash'),
                is_stale=task_dict.get('is_stale', False),
                spawned_by=task_dict.get('spawned_by', 'user')
            )
            return await self.use_case.execute(task)

    class StatusUpdaterAdapter:
        """Adapts UpdateStatusUseCase to StatusUpdater protocol."""
        def __init__(self, use_case):
            self.use_case = use_case

        def update_status(self, task_dict, status):
            """Update status by converting dict to Task entity with Phase 1 fields."""
            # Extract Phase 1 fields from dict
            phase1_fields = ['description', 'parent_priority_id', 'parent_context_hash', 'is_stale', 'spawned_by']
            metadata_keys = [k for k in task_dict.keys() if k not in ['id', 'priority', 'status'] + phase1_fields]

            task = Task(
                id=task_dict['id'],
                priority=task_dict.get('priority', 1),
                status=task_dict.get('status', 'open'),
                metadata={k: task_dict[k] for k in metadata_keys},
                description=task_dict.get('description', ''),
                parent_priority_id=task_dict.get('parent_priority_id'),
                parent_context_hash=task_dict.get('parent_context_hash'),
                is_stale=task_dict.get('is_stale', False),
                spawned_by=task_dict.get('spawned_by', 'user')
            )
            updated_task = self.use_case.execute(task, status)
            # Update the original dict in place
            task_dict['status'] = updated_task.status

    class BranchManagerAdapter:
        """Adapts ManageBranchesUseCase to BranchManager protocol."""
        def __init__(self, use_case):
            self.use_case = use_case

        async def manage_branches(self, task_dict):
            """Create branch for task."""
            branch_name = f"priority/{task_dict['id']}"
            await self.use_case.execute("create", branch_name)
            return branch_name

    class WorkflowExecutorAdapter:
        """Adapts ExecuteWorkflowUseCase to WorkflowExecutor protocol."""
        def __init__(self, use_case):
            self.use_case = use_case

        async def execute_workflow(self, task_dict, branch):
            """Execute workflow for task with Phase 1 fields."""
            # Extract Phase 1 fields from dict
            phase1_fields = ['description', 'parent_priority_id', 'parent_context_hash', 'is_stale', 'spawned_by']
            metadata_keys = [k for k in task_dict.keys() if k not in ['id', 'priority', 'status'] + phase1_fields]

            task = Task(
                id=task_dict['id'],
                priority=task_dict.get('priority', 1),
                status=task_dict.get('status', 'in_progress'),
                metadata={k: task_dict[k] for k in metadata_keys},
                description=task_dict.get('description', ''),
                parent_priority_id=task_dict.get('parent_priority_id'),
                parent_context_hash=task_dict.get('parent_context_hash'),
                is_stale=task_dict.get('is_stale', False),
                spawned_by=task_dict.get('spawned_by', 'user')
            )
            result = await self.use_case.execute(task)
            return result

    class MetricsTrackerAdapter:
        """Adapts TrackMetricsUseCase to MetricsTracker protocol."""
        def __init__(self, use_case, initial_metrics):
            self.use_case = use_case
            self.metrics = initial_metrics

        def track_metrics(self, task_dict):
            """Track metrics for task with Phase 1 fields."""
            # Extract Phase 1 fields from dict
            phase1_fields = ['description', 'parent_priority_id', 'parent_context_hash', 'is_stale', 'spawned_by']
            metadata_keys = [k for k in task_dict.keys() if k not in ['id', 'priority', 'status'] + phase1_fields]

            task = Task(
                id=task_dict['id'],
                priority=task_dict.get('priority', 1),
                status=task_dict.get('status', 'completed'),
                metadata={k: task_dict[k] for k in metadata_keys},
                description=task_dict.get('description', ''),
                parent_priority_id=task_dict.get('parent_priority_id'),
                parent_context_hash=task_dict.get('parent_context_hash'),
                is_stale=task_dict.get('is_stale', False),
                spawned_by=task_dict.get('spawned_by', 'user')
            )
            # Use fixed duration for now (would be calculated in real implementation)
            self.metrics = self.use_case.execute(self.metrics, task, success=True, duration=1.0)

    class ShutdownHandlerAdapter:
        """Adapts ShutdownUseCase to ShutdownHandler protocol."""
        def __init__(self, use_case):
            self.use_case = use_case

        async def shutdown(self):
            """Perform graceful shutdown."""
            await self.use_case.execute()

    def create_from_config(self, config_path: str):
        """
        Create PriorityWorker from configuration file.

        Args:
            config_path: Path to YAML configuration file

        Returns:
            PriorityWorker instance with all dependencies wired

        Raises:
            FileNotFoundError: If config file doesn't exist
            ValueError: If config is invalid
        """
        # Load configuration
        config_file = Path(config_path)
        if not config_file.exists():
            raise FileNotFoundError(f"Config file not found: {config_path}")

        with open(config_file, 'r') as f:
            config = yaml.safe_load(f)

        pw_config = config.get('priority_worker', {})
        if not pw_config:
            raise ValueError("Invalid config: 'priority_worker' section missing")

        # Extract config sections
        daemon_config = pw_config.get('daemon', {})
        redis_config = pw_config.get('redis', {})
        git_config = pw_config.get('git', {})
        dsl_config = pw_config.get('dsl', {})
        logging_config = pw_config.get('logging', {})
        queue_config = pw_config.get('priority_queue', {})

        # Create adapters (layer 3)
        redis_adapter = RedisAdapter({
            'host': redis_config.get('host', 'localhost'),
            'port': redis_config.get('port', 6379),
            'db': redis_config.get('db', 0)
        })

        git_adapter = GitAdapter({
            'repo_path': git_config.get('repo_path', '.')
        })

        cli_executor_adapter = CLITaskExecutorAdapter({
            'cwd': dsl_config.get('cwd', '.'),
            'timeout': dsl_config.get('timeout', 300)
        })

        logger_adapter = LoggerAdapter({
            'level': logging_config.get('level', 'INFO'),
            'format': logging_config.get('format', '%(asctime)s - %(levelname)s - %(message)s')
        })

        # Phase 1: Redis-based task polling (replaces PriorityQueueAdapter/YAML)
        # Tasks are now submitted via RedisAdapter.submit_task() and polled from Redis queue

        # Create use cases (layer 2) - wire adapters via DI
        claim_task_uc = ClaimTaskUseCase(lock_interface=redis_adapter)

        execute_workflow_uc = ExecuteWorkflowUseCase(executor_interface=cli_executor_adapter)

        manage_branches_uc = ManageBranchesUseCase(vc_interface=git_adapter)

        handle_errors_uc = HandleErrorsUseCase(
            max_retries=daemon_config.get('max_retries', 3),
            base_delay=daemon_config.get('base_delay', 1.0)
        )

        update_status_uc = UpdateStatusUseCase()

        # Create sample metrics for tracker (in real use, would persist/load)
        sample_metrics = Metrics(throughput=0.0, latency=0.0, success_rate=1.0)
        track_metrics_uc = TrackMetricsUseCase()

        shutdown_uc = ShutdownUseCase(
            lock_interface=redis_adapter,
            vc_interface=git_adapter,
            executor_interface=cli_executor_adapter
        )

        # Prepare daemon configuration for PriorityWorker
        worker_config = {
            'cycle_seconds': daemon_config.get('cycle_hours', 24) * 3600,
            'max_retries': daemon_config.get('max_retries', 3),
            'redis': redis_config,
            'git': git_config,
            'dsl': dsl_config,
            'logging': logging_config
        }

        # Create protocol adapters that bridge use cases to PriorityWorker protocol interfaces
        task_poller = self.TaskPollerAdapter(redis_adapter)  # Phase 1: Poll from Redis queue
        task_claimer = self.TaskClaimerAdapter(claim_task_uc)
        status_updater = self.StatusUpdaterAdapter(update_status_uc)
        branch_manager = self.BranchManagerAdapter(manage_branches_uc)
        workflow_executor = self.WorkflowExecutorAdapter(execute_workflow_uc)
        metrics_tracker = self.MetricsTrackerAdapter(track_metrics_uc, sample_metrics)
        shutdown_handler = self.ShutdownHandlerAdapter(shutdown_uc)

        # Create and return fully-wired PriorityWorker instance (layer 4)
        return PriorityWorker(
            task_poller=task_poller,
            task_claimer=task_claimer,
            status_updater=status_updater,
            branch_manager=branch_manager,
            workflow_executor=workflow_executor,
            metrics_tracker=metrics_tracker,
            shutdown_handler=shutdown_handler,
            config=worker_config
        )
