"""Priority Worker Factory

Factory pattern for creating PriorityWorker with all dependencies wired.

Clean Architecture: Factory (outermost layer, wiring)
SOLID: DIP (creates and wires abstractions)

Generated by ULTRATHINK (backend-lead agent) on 2025-10-04, refined for actual components.
"""

import yaml
from pathlib import Path
from typing import Dict, Any

# Import actual generated components
from src.priority_queue.entities import Task, Metrics
from src.priority_queue.use_cases import (
    ClaimTaskUseCase,
    ExecuteWorkflowUseCase,
    ManageBranchesUseCase,
    HandleErrorsUseCase,
    UpdateStatusUseCase,
    TrackMetricsUseCase,
    ShutdownUseCase
)
from src.priority_queue.adapters.redis_adapter import RedisAdapter
from src.priority_queue.adapters.git_adapter import GitAdapter
from src.priority_queue.adapters.cli_executor_adapter import CLITaskExecutorAdapter
from src.priority_queue.adapters.logger_adapter import LoggerAdapter


class PriorityWorkerFactory:
    """
    Factory for creating fully-wired PriorityWorker instances.

    Implements dependency injection by:
    1. Loading configuration from YAML
    2. Creating adapter instances with config
    3. Creating use case instances with adapters
    4. Creating PriorityWorker with all dependencies

    Example:
        factory = PriorityWorkerFactory()
        worker = factory.create_from_config('config/priority_worker.yaml')
        await worker.run()
    """

    def create_from_config(self, config_path: str):
        """
        Create PriorityWorker from configuration file.

        Args:
            config_path: Path to YAML configuration file

        Returns:
            PriorityWorker instance with all dependencies wired

        Raises:
            FileNotFoundError: If config file doesn't exist
            ValueError: If config is invalid
        """
        # Load configuration
        config_file = Path(config_path)
        if not config_file.exists():
            raise FileNotFoundError(f"Config file not found: {config_path}")

        with open(config_file, 'r') as f:
            config = yaml.safe_load(f)

        pw_config = config.get('priority_worker', {})
        if not pw_config:
            raise ValueError("Invalid config: 'priority_worker' section missing")

        # Extract config sections
        daemon_config = pw_config.get('daemon', {})
        redis_config = pw_config.get('redis', {})
        git_config = pw_config.get('git', {})
        dsl_config = pw_config.get('dsl', {})
        logging_config = pw_config.get('logging', {})

        # Create adapters (layer 3)
        redis_adapter = RedisAdapter({
            'host': redis_config.get('host', 'localhost'),
            'port': redis_config.get('port', 6379),
            'db': redis_config.get('db', 0)
        })

        git_adapter = GitAdapter({
            'repo_path': git_config.get('repo_path', '.')
        })

        cli_executor_adapter = CLITaskExecutorAdapter({
            'cwd': dsl_config.get('cwd', '.'),
            'timeout': dsl_config.get('timeout', 300)
        })

        logger_adapter = LoggerAdapter({
            'level': logging_config.get('level', 'INFO'),
            'format': logging_config.get('format', '%(asctime)s - %(levelname)s - %(message)s')
        })

        # Create use cases (layer 2) - wire adapters via DI
        claim_task_uc = ClaimTaskUseCase(lock_interface=redis_adapter)

        execute_workflow_uc = ExecuteWorkflowUseCase(executor_interface=cli_executor_adapter)

        manage_branches_uc = ManageBranchesUseCase(vc_interface=git_adapter)

        handle_errors_uc = HandleErrorsUseCase(
            max_retries=daemon_config.get('max_retries', 3),
            base_delay=daemon_config.get('base_delay', 1.0)
        )

        update_status_uc = UpdateStatusUseCase()

        # Create sample metrics for tracker (in real use, would persist/load)
        sample_metrics = Metrics(throughput=0.0, latency=0.0, success_rate=1.0)
        track_metrics_uc = TrackMetricsUseCase()

        shutdown_uc = ShutdownUseCase(
            lock_interface=redis_adapter,
            vc_interface=git_adapter,
            executor_interface=cli_executor_adapter
        )

        # Prepare daemon configuration for PriorityWorker
        worker_config = {
            'cycle_seconds': daemon_config.get('cycle_hours', 24) * 3600,
            'max_retries': daemon_config.get('max_retries', 3),
            'redis': redis_config,
            'git': git_config,
            'dsl': dsl_config,
            'logging': logging_config
        }

        # Import and create PriorityWorker (layer 4) - avoiding circular imports
        # Note: Actual wiring would pass use cases and adapters matching PriorityWorker's protocol expectations
        # For now, return configuration for manual wiring in main()
        return {
            'use_cases': {
                'claim_task': claim_task_uc,
                'execute_workflow': execute_workflow_uc,
                'manage_branches': manage_branches_uc,
                'handle_errors': handle_errors_uc,
                'update_status': update_status_uc,
                'track_metrics': track_metrics_uc,
                'shutdown': shutdown_uc
            },
            'adapters': {
                'redis': redis_adapter,
                'git': git_adapter,
                'cli_executor': cli_executor_adapter,
                'logger': logger_adapter
            },
            'config': worker_config
        }

        # TODO: Once PriorityWorker is updated to accept these dependencies,
        # return PriorityWorker(**wired_dependencies) instead of dict
