"""Priority Queue Use Cases Layer

Business logic with dependencies only on entities and interfaces.

Clean Architecture: Use Cases layer (application business rules)
SOLID: SRP (single responsibility per use case), DIP (depend on abstractions)

Generated by ULTRATHINK (devops-lead agent) on 2025-10-04.
"""

import abc
import asyncio
import logging
from typing import Any, Awaitable, Callable, Optional

from .entities import Task, Metrics

# Configure logging
logger = logging.getLogger(__name__)


# Interfaces (ABCs)
class LockInterface(abc.ABC):
    """Abstract interface for locking mechanisms to ensure atomic operations."""

    @abc.abstractmethod
    async def lock(self, resource: str) -> bool:
        """Acquire a lock on the resource. Returns True if successful."""
        pass

    @abc.abstractmethod
    async def unlock(self, resource: str) -> None:
        """Release the lock on the resource."""
        pass


class VCInterface(abc.ABC):
    """Abstract interface for version control operations."""

    @abc.abstractmethod
    async def create_branch(self, name: str) -> bool:
        """Create a new branch. Returns True if successful."""
        pass

    @abc.abstractmethod
    async def switch_branch(self, name: str) -> None:
        """Switch to the specified branch."""
        pass

    @abc.abstractmethod
    async def merge_branch(self, source: str, target: str) -> bool:
        """Merge source branch into target. Returns True if successful."""
        pass


class ExecutorInterface(abc.ABC):
    """Abstract interface for executing tasks or workflows."""

    @abc.abstractmethod
    async def execute_task(self, task: Task) -> Any:
        """Execute the given task. Returns the result."""
        pass


# Use Cases
class ClaimTaskUseCase:
    """Use case for atomically claiming a task via adapters. Depends on LockInterface."""

    def __init__(self, lock_interface: LockInterface):
        self.lock_interface = lock_interface

    async def execute(self, task: Task) -> bool:
        """Claim the task atomically. Returns True if claimed successfully."""
        try:
            locked = await self.lock_interface.lock(f"task_{task.id}")
            if locked:
                # Note: In real implementation, would update task via repository
                logger.info("Task %s claimed successfully.", task.id)
                return True
            else:
                logger.warning("Failed to lock task %s.", task.id)
                return False
        except Exception as e:
            logger.error("Error claiming task %s: %s", task.id, e)
            raise
        finally:
            await self.lock_interface.unlock(f"task_{task.id}")


class ExecuteWorkflowUseCase:
    """Use case for running a DSL workflow via CLITaskExecutor. Depends on ExecutorInterface."""

    def __init__(self, executor_interface: ExecutorInterface):
        self.executor_interface = executor_interface

    async def execute(self, task: Task) -> Any:
        """Execute the workflow for the task. Returns the execution result."""
        try:
            result = await self.executor_interface.execute_task(task)
            logger.info("Workflow executed for task %s.", task.id)
            return result
        except Exception as e:
            logger.error("Error executing workflow for task %s: %s", task.id, e)
            raise


class ManageBranchesUseCase:
    """Use case for Git branch creation and management. Depends on VCInterface."""

    def __init__(self, vc_interface: VCInterface):
        self.vc_interface = vc_interface

    async def execute(self, action: str, branch_name: str, target_branch: Optional[str] = None) -> bool:
        """Perform branch management action (create, switch, merge). Returns True if successful."""
        try:
            if action == "create":
                success = await self.vc_interface.create_branch(branch_name)
            elif action == "switch":
                await self.vc_interface.switch_branch(branch_name)
                success = True
            elif action == "merge" and target_branch:
                success = await self.vc_interface.merge_branch(branch_name, target_branch)
            else:
                raise ValueError("Invalid action or missing parameters.")
            logger.info("Branch action '%s' completed for %s.", action, branch_name)
            return success
        except Exception as e:
            logger.error("Error in branch management for %s: %s", branch_name, e)
            raise


class HandleErrorsUseCase:
    """Use case for handling errors with retry and exponential backoff."""

    def __init__(self, max_retries: int = 3, base_delay: float = 1.0):
        self.max_retries = max_retries
        self.base_delay = base_delay

    async def execute(self, func: Callable[[], Awaitable[Any]]) -> Any:
        """Execute the function with retry on failure. Returns the result."""
        for attempt in range(self.max_retries + 1):
            try:
                return await func()
            except Exception as e:
                if attempt < self.max_retries:
                    delay = self.base_delay * (2 ** attempt)
                    logger.warning("Attempt %d failed: %s. Retrying in %.2f seconds.", attempt + 1, e, delay)
                    await asyncio.sleep(delay)
                else:
                    logger.error("All retries exhausted: %s", e)
                    raise


class UpdateStatusUseCase:
    """Use case for updating task status transitions."""

    def execute(self, task: Task, new_status: str) -> Task:
        """Update the task status. Returns new Task instance (immutable entity)."""
        try:
            if not task.is_valid_status():
                raise ValueError(f"Invalid current status: {task.status}")

            # Create new Task with updated status (entities are immutable)
            from dataclasses import replace
            updated_task = replace(task, status=new_status)

            if not updated_task.is_valid_status():
                raise ValueError(f"Invalid new status: {new_status}")

            logger.info("Task %s status updated to %s.", task.id, new_status)
            return updated_task
        except Exception as e:
            logger.error("Error updating status for task %s: %s", task.id, e)
            raise


class TrackMetricsUseCase:
    """Use case for calculating and logging metrics. Uses Metrics entity."""

    def execute(self, metrics: Metrics, task: Task, success: bool, duration: float) -> Metrics:
        """Track metrics for the task. Returns updated Metrics instance (immutable)."""
        try:
            from dataclasses import replace

            # Calculate new metrics (immutable update)
            new_throughput = metrics.throughput  # Would calculate from time window
            new_latency = duration  # Task execution time
            completed_count = 1
            success_count = 1 if success else 0

            # Update success rate (weighted average)
            total_tasks = getattr(metrics.metadata, 'total_tasks', 0) + 1 if hasattr(metrics, 'metadata') else 1
            new_success_rate = (
                (metrics.success_rate * (total_tasks - 1) + success_count) / total_tasks
                if total_tasks > 0 else float(success_count)
            )

            updated_metrics = replace(
                metrics,
                throughput=new_throughput,
                latency=new_latency,
                success_rate=new_success_rate
            )

            logger.info("Metrics updated for task %s (success=%s, duration=%.2fs).",
                       task.id, success, duration)
            return updated_metrics
        except Exception as e:
            logger.error("Error tracking metrics for task %s: %s", task.id, e)
            raise


class ShutdownUseCase:
    """Use case for graceful cleanup. Depends on interfaces for cleanup."""

    def __init__(
        self,
        lock_interface: Optional[LockInterface] = None,
        vc_interface: Optional[VCInterface] = None,
        executor_interface: Optional[ExecutorInterface] = None
    ):
        self.lock_interface = lock_interface
        self.vc_interface = vc_interface
        self.executor_interface = executor_interface

    async def execute(self) -> None:
        """Perform graceful shutdown cleanup."""
        try:
            if self.lock_interface:
                # Release all locks (implementation-specific)
                logger.info("Releasing all locks during shutdown.")
            if self.vc_interface:
                # Clean up version control state
                logger.info("Cleaning up version control state.")
            if self.executor_interface:
                # Shutdown executor gracefully
                logger.info("Shutting down executor.")
            logger.info("Shutdown completed gracefully.")
        except Exception as e:
            logger.error("Error during shutdown: %s", e)
            raise
