"""Shared Test Fixtures for Priority Queue

Provides mocks and fixtures for testing priority queue components.

Generated by ULTRATHINK (testing-lead agent) on 2025-10-04, adapted for actual components.
"""

import pytest
from unittest.mock import MagicMock, AsyncMock
from typing import Dict, Any


@pytest.fixture
def sample_task():
    """Sample Task entity for testing."""
    from src.priority_queue.entities import Task
    return Task(
        id="test-task-1",
        priority=1,
        status="open",
        metadata={"workflow": "test_workflow.ct", "description": "Test task"}
    )


@pytest.fixture
def sample_metrics():
    """Sample Metrics entity for testing."""
    from src.priority_queue.entities import Metrics
    return Metrics(
        throughput=10.5,  # tasks/hour
        latency=2.5,      # seconds
        success_rate=0.95  # 95% success
    )


@pytest.fixture
def mock_redis_config():
    """Mock Redis configuration."""
    return {
        'host': 'localhost',
        'port': 6379,
        'db': 0
    }


@pytest.fixture
def mock_git_config():
    """Mock Git configuration."""
    return {
        'repo_path': '/mock/repo/path'
    }


@pytest.fixture
def mock_lock_interface():
    """Mock LockInterface for use case testing."""
    mock = AsyncMock()
    mock.lock = AsyncMock(return_value=True)
    mock.unlock = AsyncMock(return_value=None)
    return mock


@pytest.fixture
def mock_vc_interface():
    """Mock VCInterface for use case testing."""
    mock = AsyncMock()
    mock.create_branch = AsyncMock(return_value=True)
    mock.switch_branch = AsyncMock(return_value=None)
    mock.merge_branch = AsyncMock(return_value=True)
    return mock


@pytest.fixture
def mock_executor_interface():
    """Mock ExecutorInterface for use case testing."""
    mock = AsyncMock()
    mock.execute_task = AsyncMock(return_value={"status": "success", "output": "Mock result"})
    return mock


@pytest.fixture
def mock_priority_worker_config():
    """Mock PriorityWorker configuration."""
    return {
        'cycle_seconds': 60,  # 1 minute for testing
        'max_retries': 3,
        'redis': {'host': 'localhost', 'port': 6379, 'db': 0},
        'git': {'repo_path': '/mock/repo'},
        'dsl': {'cwd': '/mock/cwd', 'timeout': 30}
    }
