"""Unit Tests for Priority Queue Use Cases

Tests for use cases with mocked adapters (DIP compliance).

Generated by ULTRATHINK (testing-lead agent) on 2025-10-04.
"""

import pytest
from unittest.mock import AsyncMock
from src.priority_queue.use_cases import (
    ClaimTaskUseCase,
    ExecuteWorkflowUseCase,
    ManageBranchesUseCase,
    HandleErrorsUseCase,
    UpdateStatusUseCase,
    TrackMetricsUseCase,
    ShutdownUseCase
)


class TestClaimTaskUseCase:
    """Test cases for ClaimTaskUseCase."""

    @pytest.mark.asyncio
    async def test_claim_task_success(self, sample_task, mock_lock_interface):
        """Test successful task claiming."""
        mock_lock_interface.lock.return_value = True
        use_case = ClaimTaskUseCase(lock_interface=mock_lock_interface)

        result = await use_case.execute(sample_task)

        assert result is True
        mock_lock_interface.lock.assert_called_once()
        mock_lock_interface.unlock.assert_called_once()

    @pytest.mark.asyncio
    async def test_claim_task_failure(self, sample_task, mock_lock_interface):
        """Test failed task claiming (lock unavailable)."""
        mock_lock_interface.lock.return_value = False
        use_case = ClaimTaskUseCase(lock_interface=mock_lock_interface)

        result = await use_case.execute(sample_task)

        assert result is False


class TestExecuteWorkflowUseCase:
    """Test cases for ExecuteWorkflowUseCase."""

    @pytest.mark.asyncio
    async def test_execute_workflow_success(self, sample_task, mock_executor_interface):
        """Test successful workflow execution."""
        use_case = ExecuteWorkflowUseCase(executor_interface=mock_executor_interface)

        result = await use_case.execute(sample_task)

        assert result["status"] == "success"
        mock_executor_interface.execute_task.assert_called_once_with(sample_task)


class TestManageBranchesUseCase:
    """Test cases for ManageBranchesUseCase."""

    @pytest.mark.asyncio
    async def test_create_branch(self, mock_vc_interface):
        """Test branch creation."""
        mock_vc_interface.create_branch.return_value = True
        use_case = ManageBranchesUseCase(vc_interface=mock_vc_interface)

        result = await use_case.execute("create", "test-branch")

        assert result is True
        mock_vc_interface.create_branch.assert_called_once_with("test-branch")


class TestHandleErrorsUseCase:
    """Test cases for HandleErrorsUseCase."""

    @pytest.mark.asyncio
    async def test_retry_success_after_failures(self):
        """Test successful execution after retries."""
        use_case = HandleErrorsUseCase(max_retries=3, base_delay=0.01)

        # Mock function that fails twice then succeeds
        call_count = 0
        async def mock_func():
            nonlocal call_count
            call_count += 1
            if call_count < 3:
                raise ValueError("Mock failure")
            return "success"

        result = await use_case.execute(mock_func)

        assert result == "success"
        assert call_count == 3

    @pytest.mark.asyncio
    async def test_retry_exhaustion(self):
        """Test retry exhaustion after max attempts."""
        use_case = HandleErrorsUseCase(max_retries=2, base_delay=0.01)

        async def failing_func():
            raise ValueError("Always fails")

        with pytest.raises(ValueError, match="Always fails"):
            await use_case.execute(failing_func)


class TestUpdateStatusUseCase:
    """Test cases for UpdateStatusUseCase."""

    def test_update_status(self, sample_task):
        """Test status update."""
        use_case = UpdateStatusUseCase()

        updated_task = use_case.execute(sample_task, "completed")

        assert updated_task.status == "completed"
        assert updated_task.id == sample_task.id  # Other fields unchanged


class TestTrackMetricsUseCase:
    """Test cases for TrackMetricsUseCase."""

    def test_track_metrics_success(self, sample_metrics, sample_task):
        """Test metrics tracking for successful task."""
        use_case = TrackMetricsUseCase()

        updated_metrics = use_case.execute(sample_metrics, sample_task, success=True, duration=2.5)

        assert updated_metrics.latency == 2.5
        # Success rate should be recalculated


class TestShutdownUseCase:
    """Test cases for ShutdownUseCase."""

    @pytest.mark.asyncio
    async def test_shutdown_with_all_interfaces(
        self, mock_lock_interface, mock_vc_interface, mock_executor_interface
    ):
        """Test graceful shutdown with all interfaces."""
        use_case = ShutdownUseCase(
            lock_interface=mock_lock_interface,
            vc_interface=mock_vc_interface,
            executor_interface=mock_executor_interface
        )

        await use_case.execute()

        # Should not raise, logs cleanup messages
