"""Unit Tests for Priority Queue Entities

Tests for Task and Metrics entities with validation.

Generated by ULTRATHINK (testing-lead agent) on 2025-10-04.
"""

import pytest
from src.priority_queue.entities import Task, Metrics


class TestTask:
    """Test cases for Task entity."""

    @pytest.mark.parametrize("task_id, priority, status, metadata", [
        ("task-1", 1, "open", {"key": "value"}),
        ("task-2", 5, "claimed", {}),
        ("task-3", 0, "in_progress", {"workflow": "test.ct"}),
    ])
    def test_task_creation(self, task_id, priority, status, metadata):
        """Test Task creation with various valid inputs."""
        task = Task(id=task_id, priority=priority, status=status, metadata=metadata)
        assert task.id == task_id
        assert task.priority == priority
        assert task.status == status
        assert task.metadata == metadata

    def test_task_immutability(self, sample_task):
        """Test that Task is immutable (frozen dataclass)."""
        with pytest.raises(Exception):  # FrozenInstanceError
            sample_task.status = "modified"

    @pytest.mark.parametrize("status, expected_valid", [
        ("open", True),
        ("claimed", True),
        ("in_progress", True),
        ("completed", True),
        ("failed", True),
        ("invalid_status", False),
        ("", False),
    ])
    def test_status_validation(self, status, expected_valid):
        """Test is_valid_status() method."""
        task = Task(id="test", priority=1, status=status, metadata={})
        assert task.is_valid_status() == expected_valid


class TestMetrics:
    """Test cases for Metrics entity."""

    @pytest.mark.parametrize("throughput, latency, success_rate", [
        (0.0, 0.0, 0.0),
        (10.5, 2.5, 0.95),
        (100.0, 0.1, 1.0),
    ])
    def test_metrics_creation(self, throughput, latency, success_rate):
        """Test Metrics creation with various valid inputs."""
        metrics = Metrics(
            throughput=throughput,
            latency=latency,
            success_rate=success_rate
        )
        assert metrics.throughput == throughput
        assert metrics.latency == latency
        assert metrics.success_rate == success_rate

    def test_metrics_immutability(self, sample_metrics):
        """Test that Metrics is immutable (frozen dataclass)."""
        with pytest.raises(Exception):  # FrozenInstanceError
            sample_metrics.throughput = 99.9

    @pytest.mark.parametrize("success_rate, expected_valid", [
        (0.0, True),
        (0.5, True),
        (1.0, True),
        (-0.1, False),
        (1.1, False),
        (2.0, False),
    ])
    def test_success_rate_validation(self, success_rate, expected_valid):
        """Test is_valid_success_rate() method."""
        metrics = Metrics(throughput=1.0, latency=1.0, success_rate=success_rate)
        assert metrics.is_valid_success_rate() == expected_valid
