apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: project-builder
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  tls:
    - hosts:
        - grafana.dev.local
      secretName: grafana-tls
  rules:
    - host: grafana.dev.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000

