apiVersion: v1
kind: Service
metadata:
  name: project-builder
  namespace: project-builder
  labels:
    app.kubernetes.io/name: project-builder
    app.kubernetes.io/part-of: project-builder
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: project-builder
  ports:
    - name: http
      port: 8000
      targetPort: http

