apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: project-builder
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: project-builder
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: http

