#!/bin/bash

# scripts/deploy_pilot.sh
# Deployment automation script for PriorityWorker pilot.
# Requirements: Check prerequisites, start Redis (Docker), validate configs, run tests, start worker, monitor, status, cleanup.
# Includes error handling, logging, and user-friendly output.
# Generated by ULTRATHINK (integration-test-engineer) on 2025-10-04

set -e  # Exit on any error

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_FILE="$SCRIPT_DIR/deploy_pilot.log"
REDIS_CONTAINER_NAME="priority_worker_redis"
PRIORITY_WORKER_PID=""
REDIS_STARTED_BY_SCRIPT=false

# Colors for user-friendly output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'  # No Color

# Logging function (to file and console)
log() {
    local level="$1"
    local message="$2"
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    echo "[$timestamp] [$level] $message" >> "$LOG_FILE"
    case "$level" in
        INFO) echo -e "${GREEN}[INFO]${NC} $message" ;;
        WARN) echo -e "${YELLOW}[WARN]${NC} $message" ;;
        ERROR) echo -e "${RED}[ERROR]${NC} $message" ;;
        *) echo "$message" ;;
    esac
}

# Error handling function
error_exit() {
    local message="$1"
    log "ERROR" "$message"
    cleanup
    exit 1
}

# Cleanup function
cleanup() {
    log "INFO" "Performing cleanup..."
    if [[ -n "$PRIORITY_WORKER_PID" && -d /proc/$PRIORITY_WORKER_PID ]]; then
        log "INFO" "Stopping PriorityWorker (PID: $PRIORITY_WORKER_PID)"
        kill "$PRIORITY_WORKER_PID" 2>/dev/null || true
    fi
    if [[ "$REDIS_STARTED_BY_SCRIPT" == "true" ]]; then
        log "INFO" "Stopping Redis container ($REDIS_CONTAINER_NAME)"
        docker stop "$REDIS_CONTAINER_NAME" 2>/dev/null || true
        docker rm "$REDIS_CONTAINER_NAME" 2>/dev/null || true
    fi
    log "INFO" "Cleanup complete."
}

# Trap for cleanup on exit or interrupt
trap cleanup EXIT INT TERM

# Function to check prerequisites
check_prereqs() {
    log "INFO" "Checking prerequisites..."

    # Check if Docker is installed
    if ! command -v docker &> /dev/null; then
        error_exit "Docker is not installed or not in PATH. Please install Docker."
    fi

    # Check if Python is installed
    if ! command -v python3 &> /dev/null; then
        error_exit "Python3 is not installed or not in PATH. Please install Python3."
    fi

    # Check Python dependencies (assume requirements.txt or simple pip check)
    if [[ -f "$SCRIPT_DIR/../requirements.txt" ]]; then
        if ! python3 -m pip list | grep -q -f "$SCRIPT_DIR/../requirements.txt"; then
            log "WARN" "Python dependencies may be missing. Attempting to install..."
            python3 -m pip install -r "$SCRIPT_DIR/../requirements.txt" || error_exit "Failed to install Python dependencies."
        fi
    else
        log "WARN" "requirements.txt not found. Assuming dependencies are met."
    fi

    # Check if Redis is running (via docker or local)
    if ! docker ps | grep -q "$REDIS_CONTAINER_NAME" && ! command -v redis-cli &> /dev/null || ! redis-cli ping &> /dev/null; then
        log "INFO" "Redis is not running. Will start via Docker."
    else
        log "INFO" "Redis is already running."
    fi

    log "INFO" "Prerequisites check passed."
}

# Function to start Redis if not running
start_redis() {
    if docker ps | grep -q "$REDIS_CONTAINER_NAME" || (command -v redis-cli &> /dev/null && redis-cli ping &> /dev/null); then
        log "INFO" "Redis is already running. Skipping start."
        return
    fi

    log "INFO" "Starting Redis via Docker..."
    docker run -d --name "$REDIS_CONTAINER_NAME" -p 6379:6379 redis:alpine || error_exit "Failed to start Redis container."
    REDIS_STARTED_BY_SCRIPT=true

    # Wait for Redis to be ready
    sleep 5
    if ! docker exec "$REDIS_CONTAINER_NAME" redis-cli ping &> /dev/null; then
        error_exit "Redis failed to start properly."
    fi
    log "INFO" "Redis started successfully."
}

# Function to validate configuration files
validate_configs() {
    log "INFO" "Validating configuration files..."

    if [[ ! -f "$SCRIPT_DIR/../config/priority_worker.yaml" ]]; then
        error_exit "Configuration file config/priority_worker.yaml not found."
    fi

    if [[ ! -f "$SCRIPT_DIR/../config/priorities.yaml" ]]; then
        error_exit "Configuration file config/priorities.yaml not found."
    fi

    log "INFO" "Configuration files validated."
}

# Function to run integration tests
run_integration_tests() {
    log "INFO" "Running integration tests..."

    if [[ ! -f "$SCRIPT_DIR/test_priority_worker_integration.py" ]]; then
        error_exit "Integration test script not found: scripts/test_priority_worker_integration.py"
    fi

    if ! python3 "$SCRIPT_DIR/test_priority_worker_integration.py"; then
        error_exit "Integration tests failed. Aborting deployment."
    fi

    log "INFO" "Integration tests passed."
}

# Function to start PriorityWorker in background
start_priority_worker() {
    log "INFO" "Starting PriorityWorker in background..."

    if [[ ! -f "$SCRIPT_DIR/priority_worker.py" ]]; then
        error_exit "PriorityWorker script not found: scripts/priority_worker.py"
    fi

    python3 "$SCRIPT_DIR/priority_worker.py" --config "$SCRIPT_DIR/../config/priority_worker.yaml" >> "$LOG_FILE" 2>&1 &
    PRIORITY_WORKER_PID=$!
    log "INFO" "PriorityWorker started with PID: $PRIORITY_WORKER_PID"
}

# Function to monitor initial execution
monitor_execution() {
    log "INFO" "Monitoring PriorityWorker for the first 60 seconds..."

    local count=0
    while [[ $count -lt 60 ]]; do
        if ! kill -0 "$PRIORITY_WORKER_PID" 2>/dev/null; then
            error_exit "PriorityWorker process (PID: $PRIORITY_WORKER_PID) stopped unexpectedly."
        fi
        sleep 1
        ((count++))
    done

    log "INFO" "Monitoring complete. PriorityWorker is running stably."
}

# Function to provide status and next steps
provide_status() {
    log "INFO" "Deployment status:"
    echo -e "${GREEN}✓ Prerequisites checked${NC}"
    echo -e "${GREEN}✓ Redis running${NC}"
    echo -e "${GREEN}✓ Configurations validated${NC}"
    echo -e "${GREEN}✓ Integration tests passed${NC}"
    echo -e "${GREEN}✓ PriorityWorker started (PID: $PRIORITY_WORKER_PID)${NC}"
    echo -e "${GREEN}✓ Initial monitoring complete${NC}"
    log "INFO" "Next steps:"
    echo -e "${YELLOW}• Monitor logs in $LOG_FILE${NC}"
    echo -e "${YELLOW}• Check PriorityWorker output manually if needed${NC}"
    echo -e "${YELLOW}• To stop: Run 'pkill -f priority_worker.py' or use cleanup commands${NC}"
    echo -e "${GREEN}Pilot deployment successful!${NC}"
}

# Main execution
log "INFO" "Starting PriorityWorker pilot deployment..."
check_prereqs
start_redis
validate_configs
run_integration_tests
start_priority_worker
monitor_execution
provide_status
log "INFO" "Deployment script completed successfully."
