#!/usr/bin/env python3
"""Priority Worker Orchestrator

Main daemon that orchestrates autonomous priority execution using
Clean Architecture composition of entities, use cases, and adapters.

Clean Architecture: Orchestrator (outermost layer, composes all others)
SOLID: SRP (orchestration only), DIP (depends on abstractions)

Generated by ULTRATHINK (category-theory-expert agent) on 2025-10-04.

Usage:
    python3 scripts/priority_worker.py --config config/priority_worker.yaml

    Or run in loop mode:
    python3 scripts/priority_worker.py --config config/priority_worker.yaml --loop
"""

import asyncio
import logging
import signal
import time
import yaml
import argparse
from typing import Protocol, List, Dict, Any
from pathlib import Path


# Protocols for Dependency Injection (DIP: depend on abstractions)
class TaskPoller(Protocol):
    """Protocol for polling open tasks from priority queue."""
    def poll_tasks(self) -> List[Dict[str, Any]]: ...


class TaskClaimer(Protocol):
    """Protocol for atomic task claiming."""
    def claim_task(self, task: Dict[str, Any]) -> bool: ...


class StatusUpdater(Protocol):
    """Protocol for updating task status."""
    def update_status(self, task: Dict[str, Any], status: str) -> None: ...


class BranchManager(Protocol):
    """Protocol for Git branch management."""
    def manage_branches(self, task: Dict[str, Any]) -> str: ...


class WorkflowExecutor(Protocol):
    """Protocol for DSL workflow execution."""
    async def execute_workflow(self, task: Dict[str, Any], branch: str) -> Dict[str, Any]: ...


class MetricsTracker(Protocol):
    """Protocol for metrics tracking."""
    def track_metrics(self, task: Dict[str, Any]) -> None: ...


class ShutdownHandler(Protocol):
    """Protocol for graceful shutdown."""
    def shutdown(self) -> None: ...


# Global shutdown event for signal handling
shutdown_event = asyncio.Event()


def signal_handler(signum, frame):
    """Handle SIGTERM and SIGINT for graceful shutdown."""
    logging.info(f"Received signal {signum}, initiating shutdown.")
    shutdown_event.set()


class PriorityWorker:
    """
    Orchestrator class for autonomous priority execution.

    Follows Clean Architecture and SOLID principles:
    - SRP: Only orchestrates, no business logic
    - DIP: Depends on abstractions (protocols)
    - Composition: All dependencies injected via constructor

    Attributes:
        task_poller: Polls open tasks from queue
        task_claimer: Claims tasks atomically
        status_updater: Updates task status
        branch_manager: Manages Git branches
        workflow_executor: Executes DSL workflows
        metrics_tracker: Tracks execution metrics
        shutdown_handler: Handles graceful shutdown
        config: Configuration dictionary
        cycle_duration: Duration of each cycle in seconds (default 24h)
    """

    def __init__(
        self,
        task_poller: TaskPoller,
        task_claimer: TaskClaimer,
        status_updater: StatusUpdater,
        branch_manager: BranchManager,
        workflow_executor: WorkflowExecutor,
        metrics_tracker: MetricsTracker,
        shutdown_handler: ShutdownHandler,
        config: Dict[str, Any]
    ):
        """Initialize PriorityWorker with all dependencies via DI."""
        self.task_poller = task_poller
        self.task_claimer = task_claimer
        self.status_updater = status_updater
        self.branch_manager = branch_manager
        self.workflow_executor = workflow_executor
        self.metrics_tracker = metrics_tracker
        self.shutdown_handler = shutdown_handler
        self.config = config
        self.cycle_duration = config.get('cycle_seconds', 86400)  # Default 24 hours

    async def run(self):
        """
        Main run loop implementing the orchestration algorithm.

        Algorithm:
        1. Poll open tasks from priority queue
        2. For each task:
           a. Attempt atomic claim
           b. If claimed: update status to in_progress
           c. Create/manage Git branch
           d. Execute DSL workflow
           e. Update status based on result
           f. Track metrics
        3. Sleep for remaining cycle duration
        4. Repeat until shutdown signal

        Handles graceful shutdown on SIGTERM/SIGINT.
        """
        while not shutdown_event.is_set():
            start_time = time.perf_counter()
            logging.info("Starting task polling cycle.")

            try:
                open_tasks = self.task_poller.poll_tasks()
                logging.info(f"Polled {len(open_tasks)} open tasks.")

                for task in open_tasks:
                    if shutdown_event.is_set():
                        logging.info("Shutdown signal received, skipping remaining tasks.")
                        break

                    if await self.task_claimer.claim_task(task):
                        logging.info(f"Claimed task {task.get('id')}.")
                        self.status_updater.update_status(task, 'in_progress')

                        branch = await self.branch_manager.manage_branches(task)
                        logging.info(f"Managed branches for task {task.get('id')}: {branch}")

                        result = await self.workflow_executor.execute_workflow(task, branch)
                        success = result.get('success', False)
                        status = 'completed' if success else 'failed'
                        self.status_updater.update_status(task, status)
                        logging.info(f"Task {task.get('id')} {status}.")

                        self.metrics_tracker.track_metrics(task)
                        logging.info(f"Tracked metrics for task {task.get('id')}.")
                    else:
                        logging.warning(f"Failed to claim task {task.get('id')}.")

            except Exception as e:
                logging.error(f"Error in run loop: {e}", exc_info=True)

            elapsed = time.perf_counter() - start_time
            sleep_time = max(0, self.cycle_duration - elapsed)
            logging.info(f"Cycle completed in {elapsed:.2f}s, sleeping for {sleep_time:.2f}s.")

            try:
                await asyncio.wait_for(asyncio.sleep(sleep_time), timeout=sleep_time)
            except asyncio.TimeoutError:
                pass  # Normal if interrupted by shutdown

        logging.info("Run loop exited, performing shutdown.")
        await self.shutdown_handler.shutdown()

    async def run_once(self):
        """
        Execute a single cycle of the orchestration algorithm.

        Used for pilot mode and testing. Executes one iteration without
        the infinite loop or shutdown handling.
        """
        start_time = time.perf_counter()
        logging.info("Starting single task polling cycle.")

        try:
            open_tasks = self.task_poller.poll_tasks()
            logging.info(f"Polled {len(open_tasks)} open tasks.")

            for task in open_tasks:
                if await self.task_claimer.claim_task(task):
                    logging.info(f"Claimed task {task.get('id')}.")
                    self.status_updater.update_status(task, 'in_progress')

                    branch = await self.branch_manager.manage_branches(task)
                    logging.info(f"Managed branches for task {task.get('id')}: {branch}")

                    result = await self.workflow_executor.execute_workflow(task, branch)
                    success = result.get('success', False)
                    status = 'completed' if success else 'failed'
                    self.status_updater.update_status(task, status)
                    logging.info(f"Task {task.get('id')} {status}.")

                    self.metrics_tracker.track_metrics(task)
                    logging.info(f"Tracked metrics for task {task.get('id')}.")
                else:
                    logging.warning(f"Failed to claim task {task.get('id')}.")

        except Exception as e:
            logging.error(f"Error in run_once: {e}", exc_info=True)

        elapsed = time.perf_counter() - start_time
        logging.info(f"Single cycle completed in {elapsed:.2f}s.")


def load_config(config_path: str) -> Dict[str, Any]:
    """Load configuration from YAML file.

    Args:
        config_path: Path to YAML configuration file

    Returns:
        Configuration dictionary

    Raises:
        FileNotFoundError: If config file doesn't exist
        yaml.YAMLError: If config file is invalid YAML
    """
    config_file = Path(config_path)
    if not config_file.exists():
        raise FileNotFoundError(f"Config file not found: {config_path}")

    with open(config_file, 'r') as f:
        return yaml.safe_load(f)


def main():
    """Main entrypoint: Parse args, load config, set up DI, handle signals, run orchestrator."""
    parser = argparse.ArgumentParser(description='PriorityWorker autonomous daemon')
    parser.add_argument('--config', required=True, help='Path to YAML config file')
    parser.add_argument('--loop', action='store_true', help='Run in continuous loop mode')
    args = parser.parse_args()

    # Configure logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    logger = logging.getLogger(__name__)

    try:
        # Load configuration
        config = load_config(args.config)
        logger.info(f"Loaded configuration from {args.config}")

        # TODO: Create actual dependency implementations
        # For now, this serves as the integration point where:
        # 1. PriorityQueueAdapter polls priorities.yaml
        # 2. RedisAdapter handles atomic claiming
        # 3. GitAdapter manages branches
        # 4. CLITaskExecutor runs DSL workflows
        # 5. MetricsAdapter tracks throughput/latency
        #
        # These will be wired via PriorityWorkerFactory (Task 5)

        # Set up signal handling
        signal.signal(signal.SIGTERM, signal_handler)
        signal.signal(signal.SIGINT, signal_handler)
        logger.info("Signal handlers registered (SIGTERM, SIGINT).")

        # Wire dependencies via factory
        from src.priority_queue.factory import PriorityWorkerFactory
        factory = PriorityWorkerFactory()
        worker = factory.create_from_config(args.config)

        logger.info("PriorityWorker initialized successfully.")

        # Run the orchestrator
        if args.loop:
            logger.info("Starting PriorityWorker in continuous loop mode...")
            asyncio.run(worker.run())
        else:
            logger.info("Running PriorityWorker single cycle...")
            asyncio.run(worker.run_once())

    except FileNotFoundError as e:
        logger.error(f"Configuration error: {e}")
        return 1
    except yaml.YAMLError as e:
        logger.error(f"Invalid YAML configuration: {e}")
        return 1
    except KeyboardInterrupt:
        logger.info("Interrupted by user.")
        return 0
    except Exception as e:
        logger.error(f"Unexpected error: {e}", exc_info=True)
        return 1

    return 0


if __name__ == '__main__':
    exit(main())
